/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AdmAluno;

import AdmFuncion�rio.*;
import Principal.*;

/**
 *
 * @author GabrielFelipe
 */
public class OpAlunos extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public OpAlunos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VoltarAlun = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        TelaAlun = new javax.swing.JTabbedPane();
        AbaAlun = new javax.swing.JPanel();
        foto = new javax.swing.JLabel();
        TelefoneAlun = new javax.swing.JLabel();
        telefoneAlun = new javax.swing.JLabel();
        EmailAlun = new javax.swing.JLabel();
        emailAlun = new javax.swing.JLabel();
        NomeAlun = new javax.swing.JLabel();
        nomeAlun = new javax.swing.JLabel();
        CPFAlun = new javax.swing.JLabel();
        cpfAlun = new javax.swing.JLabel();
        SexoAlun = new javax.swing.JLabel();
        sexoAlun = new javax.swing.JLabel();
        NutriAlun = new javax.swing.JLabel();
        nutriAlun = new javax.swing.JLabel();
        PagaAlun = new javax.swing.JLabel();
        pagaAlun = new javax.swing.JLabel();
        DataNascAlun = new javax.swing.JLabel();
        dataNascAlun = new javax.swing.JLabel();
        AbaCadAlun = new javax.swing.JPanel();
        fotoCadAlun = new javax.swing.JLabel();
        AdicionarFotoAlun = new javax.swing.JButton();
        NomeCadAlun = new javax.swing.JLabel();
        nomeCadAlun = new javax.swing.JTextField();
        CPFCadAlun = new javax.swing.JLabel();
        cpfCadAlun = new javax.swing.JTextField();
        NutriCadAlun = new javax.swing.JLabel();
        nutriCadAlun = new javax.swing.JComboBox<>();
        SexoCadAlun = new javax.swing.JLabel();
        sexoCadAlun = new javax.swing.JTextField();
        DataNascCadAlun = new javax.swing.JLabel();
        dataNascCadAlun = new com.toedter.calendar.JDateChooser();
        TelefoneCadAlun = new javax.swing.JLabel();
        telefoneCadAlun = new javax.swing.JTextField();
        EmailCadAlun = new javax.swing.JLabel();
        emailCadAlun = new javax.swing.JTextField();
        DataPagaCadAlun = new javax.swing.JLabel();
        dataPagaCadAlun = new com.toedter.calendar.JDateChooser();
        CadastrarAlun = new javax.swing.JButton();
        EditarAlun = new javax.swing.JButton();
        ExcluirAlun = new javax.swing.JButton();
        AbaReciboAlun = new javax.swing.JPanel();
        Texto1 = new javax.swing.JLabel();
        nomeRecAlun = new javax.swing.JTextField();
        Texto2 = new javax.swing.JLabel();
        precoRecAlun = new javax.swing.JTextField();
        Texto3 = new javax.swing.JLabel();
        dataRecAlun = new com.toedter.calendar.JDateChooser();
        Assinatura1RecAlun = new javax.swing.JLabel();
        Assinatura2RecAlun = new javax.swing.JLabel();
        SalvarRecAlun = new javax.swing.JButton();
        AbaAvaliacaoAlun = new javax.swing.JPanel();
        SalvarAvaAlun = new javax.swing.JButton();
        AbaFichaAlun = new javax.swing.JPanel();
        SalvarFichaAlun = new javax.swing.JButton();
        TabelaPesquisaAlun = new javax.swing.JPanel();
        PesquisarAlun = new javax.swing.JButton();
        pesquisarAlun = new javax.swing.JTextField();
        ScrollTabelaAlun = new javax.swing.JScrollPane();
        TabelaAlun = new javax.swing.JTable();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(1000, 640));
        setName("Login"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 640));
        getContentPane().setLayout(null);

        VoltarAlun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Voltar.png"))); // NOI18N
        VoltarAlun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarAlunActionPerformed(evt);
            }
        });
        getContentPane().add(VoltarAlun);
        VoltarAlun.setBounds(0, 0, 60, 40);

        Titulo.setFont(new java.awt.Font("Impact", 0, 30)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Administrador");
        getContentPane().add(Titulo);
        Titulo.setBounds(0, 10, 1000, 30);

        TelaAlun.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        AbaAlun.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        foto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TelefoneAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        TelefoneAlun.setText("Telefone:");

        telefoneAlun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        telefoneAlun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        telefoneAlun.setText("Null");
        telefoneAlun.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        EmailAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        EmailAlun.setText("Email:");

        emailAlun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        emailAlun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emailAlun.setText("Null");
        emailAlun.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        NomeAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        NomeAlun.setText("Nome:");

        nomeAlun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nomeAlun.setText("Null");

        CPFAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        CPFAlun.setText("CPF:");

        cpfAlun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cpfAlun.setText("Null");

        SexoAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        SexoAlun.setText("Sexo:");

        sexoAlun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        sexoAlun.setText("Null");

        NutriAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        NutriAlun.setText("Nutricionista: ");

        nutriAlun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nutriAlun.setText("Null");

        PagaAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        PagaAlun.setText("Dia de Pagamento");

        pagaAlun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        pagaAlun.setText("Null");

        DataNascAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        DataNascAlun.setText("Data de Nasc:");

        dataNascAlun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        dataNascAlun.setText("Null");

        javax.swing.GroupLayout AbaAlunLayout = new javax.swing.GroupLayout(AbaAlun);
        AbaAlun.setLayout(AbaAlunLayout);
        AbaAlunLayout.setHorizontalGroup(
            AbaAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaAlunLayout.createSequentialGroup()
                .addGroup(AbaAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbaAlunLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AbaAlunLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(AbaAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AbaAlunLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(TelefoneAlun)
                                .addGap(35, 35, 35))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AbaAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(AbaAlunLayout.createSequentialGroup()
                                    .addGap(57, 57, 57)
                                    .addComponent(EmailAlun)
                                    .addGap(34, 34, 34))
                                .addComponent(emailAlun, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(telefoneAlun, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)))
                .addGroup(AbaAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbaAlunLayout.createSequentialGroup()
                        .addComponent(NomeAlun)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomeAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AbaAlunLayout.createSequentialGroup()
                        .addGroup(AbaAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AbaAlunLayout.createSequentialGroup()
                                .addComponent(CPFAlun)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cpfAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AbaAlunLayout.createSequentialGroup()
                                .addComponent(SexoAlun)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sexoAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AbaAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AbaAlunLayout.createSequentialGroup()
                                .addComponent(DataNascAlun)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dataNascAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AbaAlunLayout.createSequentialGroup()
                                .addComponent(PagaAlun)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pagaAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(AbaAlunLayout.createSequentialGroup()
                        .addComponent(NutriAlun)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nutriAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AbaAlunLayout.setVerticalGroup(
            AbaAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AbaAlunLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(AbaAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AbaAlunLayout.createSequentialGroup()
                        .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(TelefoneAlun))
                    .addGroup(AbaAlunLayout.createSequentialGroup()
                        .addGroup(AbaAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NomeAlun)
                            .addComponent(nomeAlun))
                        .addGap(18, 18, 18)
                        .addGroup(AbaAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AbaAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(CPFAlun)
                                .addComponent(cpfAlun))
                            .addGroup(AbaAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(PagaAlun)
                                .addComponent(pagaAlun)))
                        .addGap(18, 18, 18)
                        .addGroup(AbaAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SexoAlun)
                            .addComponent(sexoAlun)
                            .addComponent(DataNascAlun)
                            .addComponent(dataNascAlun))))
                .addGroup(AbaAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbaAlunLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telefoneAlun)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EmailAlun)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailAlun))
                    .addGroup(AbaAlunLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(AbaAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NutriAlun)
                            .addComponent(nutriAlun))))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        TelaAlun.addTab("Alunos", AbaAlun);

        AbaCadAlun.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        fotoCadAlun.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        AdicionarFotoAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        AdicionarFotoAlun.setText("Adicionar");

        NomeCadAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        NomeCadAlun.setText("Nome:");

        nomeCadAlun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nomeCadAlun.setPreferredSize(new java.awt.Dimension(74, 32));

        CPFCadAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        CPFCadAlun.setText("CPF:");

        cpfCadAlun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cpfCadAlun.setPreferredSize(new java.awt.Dimension(74, 32));

        NutriCadAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        NutriCadAlun.setText("Nutricionista:");

        nutriCadAlun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        SexoCadAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        SexoCadAlun.setText("Sexo:");

        sexoCadAlun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        sexoCadAlun.setPreferredSize(new java.awt.Dimension(74, 32));

        DataNascCadAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        DataNascCadAlun.setText("Data de Nasc:");

        dataNascCadAlun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        TelefoneCadAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        TelefoneCadAlun.setText("Telefone:");

        telefoneCadAlun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        telefoneCadAlun.setPreferredSize(new java.awt.Dimension(74, 32));

        EmailCadAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        EmailCadAlun.setText("Email:");

        emailCadAlun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        emailCadAlun.setPreferredSize(new java.awt.Dimension(74, 32));

        DataPagaCadAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        DataPagaCadAlun.setText("Dia de Pagamento:");

        dataPagaCadAlun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        CadastrarAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        CadastrarAlun.setText("Cadastrar");

        EditarAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        EditarAlun.setText("Editar");

        ExcluirAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        ExcluirAlun.setText("Excluir");

        javax.swing.GroupLayout AbaCadAlunLayout = new javax.swing.GroupLayout(AbaCadAlun);
        AbaCadAlun.setLayout(AbaCadAlunLayout);
        AbaCadAlunLayout.setHorizontalGroup(
            AbaCadAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaCadAlunLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(AbaCadAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fotoCadAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdicionarFotoAlun))
                .addGap(18, 18, 18)
                .addGroup(AbaCadAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbaCadAlunLayout.createSequentialGroup()
                        .addGroup(AbaCadAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(AbaCadAlunLayout.createSequentialGroup()
                                .addComponent(TelefoneCadAlun)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(telefoneCadAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(EmailCadAlun)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emailCadAlun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(AbaCadAlunLayout.createSequentialGroup()
                                .addComponent(NomeCadAlun)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomeCadAlun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(AbaCadAlunLayout.createSequentialGroup()
                                .addGroup(AbaCadAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AbaCadAlunLayout.createSequentialGroup()
                                        .addComponent(SexoCadAlun)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(sexoCadAlun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AbaCadAlunLayout.createSequentialGroup()
                                        .addComponent(CPFCadAlun)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cpfCadAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(AbaCadAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(AbaCadAlunLayout.createSequentialGroup()
                                        .addComponent(NutriCadAlun)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nutriCadAlun, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(AbaCadAlunLayout.createSequentialGroup()
                                        .addComponent(DataNascCadAlun)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dataNascCadAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(88, 88, 88)
                        .addGroup(AbaCadAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ExcluirAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CadastrarAlun)
                            .addComponent(EditarAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AbaCadAlunLayout.createSequentialGroup()
                        .addComponent(DataPagaCadAlun)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataPagaCadAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        AbaCadAlunLayout.setVerticalGroup(
            AbaCadAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaCadAlunLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(fotoCadAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AdicionarFotoAlun)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(AbaCadAlunLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(AbaCadAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbaCadAlunLayout.createSequentialGroup()
                        .addGroup(AbaCadAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NomeCadAlun)
                            .addComponent(nomeCadAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AbaCadAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AbaCadAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(CPFCadAlun)
                                .addComponent(cpfCadAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AbaCadAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(NutriCadAlun)
                                .addComponent(nutriCadAlun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(AbaCadAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AbaCadAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SexoCadAlun)
                                .addComponent(DataNascCadAlun)
                                .addComponent(sexoCadAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dataNascCadAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(AbaCadAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TelefoneCadAlun)
                            .addComponent(telefoneCadAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmailCadAlun)
                            .addComponent(emailCadAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AbaCadAlunLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(CadastrarAlun)
                        .addGap(18, 18, 18)
                        .addComponent(EditarAlun)
                        .addGap(18, 18, 18)
                        .addComponent(ExcluirAlun)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(AbaCadAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dataPagaCadAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DataPagaCadAlun))
                .addGap(210, 210, 210))
        );

        TelaAlun.addTab("Controle", AbaCadAlun);

        AbaReciboAlun.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Texto1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Texto1.setText("Recebemos de ");

        nomeRecAlun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nomeRecAlun.setPreferredSize(new java.awt.Dimension(74, 32));

        Texto2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Texto2.setText("a quantia de ");

        precoRecAlun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        precoRecAlun.setPreferredSize(new java.awt.Dimension(74, 32));

        Texto3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Texto3.setText("correspondente ao pagamento mensal como aluno referente a data ");

        dataRecAlun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        Assinatura1RecAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        Assinatura1RecAlun.setText("_________________________________________________");

        Assinatura2RecAlun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Assinatura2RecAlun.setText("Assinatura");

        SalvarRecAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        SalvarRecAlun.setText("Salvar e Imprimir");
        SalvarRecAlun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarRecAlunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AbaReciboAlunLayout = new javax.swing.GroupLayout(AbaReciboAlun);
        AbaReciboAlun.setLayout(AbaReciboAlunLayout);
        AbaReciboAlunLayout.setHorizontalGroup(
            AbaReciboAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaReciboAlunLayout.createSequentialGroup()
                .addGroup(AbaReciboAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbaReciboAlunLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(AbaReciboAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AbaReciboAlunLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(AbaReciboAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Assinatura1RecAlun)
                                    .addGroup(AbaReciboAlunLayout.createSequentialGroup()
                                        .addGap(197, 197, 197)
                                        .addComponent(Assinatura2RecAlun)))
                                .addGap(119, 119, 119))
                            .addGroup(AbaReciboAlunLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(Texto3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dataRecAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AbaReciboAlunLayout.createSequentialGroup()
                                .addComponent(Texto1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomeRecAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Texto2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(precoRecAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(AbaReciboAlunLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SalvarRecAlun)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        AbaReciboAlunLayout.setVerticalGroup(
            AbaReciboAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaReciboAlunLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SalvarRecAlun)
                .addGap(30, 30, 30)
                .addGroup(AbaReciboAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Texto1)
                    .addComponent(nomeRecAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Texto2)
                    .addComponent(precoRecAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AbaReciboAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Texto3)
                    .addComponent(dataRecAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(Assinatura1RecAlun)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Assinatura2RecAlun)
                .addGap(207, 207, 207))
        );

        TelaAlun.addTab("Recibo", AbaReciboAlun);

        AbaAvaliacaoAlun.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        SalvarAvaAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        SalvarAvaAlun.setText("Salvar e Imprimir");
        SalvarAvaAlun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarAvaAlunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AbaAvaliacaoAlunLayout = new javax.swing.GroupLayout(AbaAvaliacaoAlun);
        AbaAvaliacaoAlun.setLayout(AbaAvaliacaoAlunLayout);
        AbaAvaliacaoAlunLayout.setHorizontalGroup(
            AbaAvaliacaoAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaAvaliacaoAlunLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SalvarAvaAlun)
                .addContainerGap(736, Short.MAX_VALUE))
        );
        AbaAvaliacaoAlunLayout.setVerticalGroup(
            AbaAvaliacaoAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaAvaliacaoAlunLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SalvarAvaAlun)
                .addGap(401, 401, 401))
        );

        TelaAlun.addTab("Avaliação", AbaAvaliacaoAlun);

        AbaFichaAlun.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        SalvarFichaAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        SalvarFichaAlun.setText("Salvar e Imprimir");
        SalvarFichaAlun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarFichaAlunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AbaFichaAlunLayout = new javax.swing.GroupLayout(AbaFichaAlun);
        AbaFichaAlun.setLayout(AbaFichaAlunLayout);
        AbaFichaAlunLayout.setHorizontalGroup(
            AbaFichaAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaFichaAlunLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SalvarFichaAlun)
                .addContainerGap(736, Short.MAX_VALUE))
        );
        AbaFichaAlunLayout.setVerticalGroup(
            AbaFichaAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaFichaAlunLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SalvarFichaAlun)
                .addGap(401, 401, 401))
        );

        TelaAlun.addTab("Ficha", AbaFichaAlun);

        getContentPane().add(TelaAlun);
        TelaAlun.setBounds(50, 40, 900, 300);

        TabelaPesquisaAlun.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        PesquisarAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        PesquisarAlun.setText("Pesquisar");

        pesquisarAlun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        pesquisarAlun.setPreferredSize(new java.awt.Dimension(74, 32));

        TabelaAlun.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TabelaAlun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TabelaAlun.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "CPF", "Dia de Pagameno"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaAlun.setToolTipText("");
        TabelaAlun.setAlignmentX(1.0F);
        TabelaAlun.setAlignmentY(1.0F);
        TabelaAlun.setRowHeight(28);
        ScrollTabelaAlun.setViewportView(TabelaAlun);

        javax.swing.GroupLayout TabelaPesquisaAlunLayout = new javax.swing.GroupLayout(TabelaPesquisaAlun);
        TabelaPesquisaAlun.setLayout(TabelaPesquisaAlunLayout);
        TabelaPesquisaAlunLayout.setHorizontalGroup(
            TabelaPesquisaAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabelaPesquisaAlunLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PesquisarAlun)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pesquisarAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TabelaPesquisaAlunLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ScrollTabelaAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        TabelaPesquisaAlunLayout.setVerticalGroup(
            TabelaPesquisaAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabelaPesquisaAlunLayout.createSequentialGroup()
                .addGroup(TabelaPesquisaAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PesquisarAlun)
                    .addComponent(pesquisarAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(ScrollTabelaAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(TabelaPesquisaAlun);
        TabelaPesquisaAlun.setBounds(50, 340, 900, 240);

        Background.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        Background.setPreferredSize(new java.awt.Dimension(1000, 570));
        getContentPane().add(Background);
        Background.setBounds(0, 0, 1000, 640);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SalvarRecAlunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarRecAlunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalvarRecAlunActionPerformed

    private void SalvarAvaAlunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarAvaAlunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalvarAvaAlunActionPerformed

    private void VoltarAlunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarAlunActionPerformed
        // Botão Voltar

        AdmSelecao AS = new AdmSelecao();
        AS.setVisible(true);
        dispose();
    }//GEN-LAST:event_VoltarAlunActionPerformed

    private void SalvarFichaAlunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarFichaAlunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalvarFichaAlunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpAlunos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AbaAlun;
    private javax.swing.JPanel AbaAvaliacaoAlun;
    private javax.swing.JPanel AbaCadAlun;
    private javax.swing.JPanel AbaFichaAlun;
    private javax.swing.JPanel AbaReciboAlun;
    private javax.swing.JButton AdicionarFotoAlun;
    private javax.swing.JLabel Assinatura1RecAlun;
    private javax.swing.JLabel Assinatura2RecAlun;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel CPFAlun;
    private javax.swing.JLabel CPFCadAlun;
    private javax.swing.JButton CadastrarAlun;
    private javax.swing.JLabel DataNascAlun;
    private javax.swing.JLabel DataNascCadAlun;
    private javax.swing.JLabel DataPagaCadAlun;
    private javax.swing.JButton EditarAlun;
    private javax.swing.JLabel EmailAlun;
    private javax.swing.JLabel EmailCadAlun;
    private javax.swing.JButton ExcluirAlun;
    private javax.swing.JLabel NomeAlun;
    private javax.swing.JLabel NomeCadAlun;
    private javax.swing.JLabel NutriAlun;
    private javax.swing.JLabel NutriCadAlun;
    private javax.swing.JLabel PagaAlun;
    private javax.swing.JButton PesquisarAlun;
    private javax.swing.JButton SalvarAvaAlun;
    private javax.swing.JButton SalvarFichaAlun;
    private javax.swing.JButton SalvarRecAlun;
    private javax.swing.JScrollPane ScrollTabelaAlun;
    private javax.swing.JLabel SexoAlun;
    private javax.swing.JLabel SexoCadAlun;
    private javax.swing.JTable TabelaAlun;
    private javax.swing.JPanel TabelaPesquisaAlun;
    private javax.swing.JTabbedPane TelaAlun;
    private javax.swing.JLabel TelefoneAlun;
    private javax.swing.JLabel TelefoneCadAlun;
    private javax.swing.JLabel Texto1;
    private javax.swing.JLabel Texto2;
    private javax.swing.JLabel Texto3;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton VoltarAlun;
    private javax.swing.JLabel cpfAlun;
    private javax.swing.JTextField cpfCadAlun;
    private javax.swing.JLabel dataNascAlun;
    private com.toedter.calendar.JDateChooser dataNascCadAlun;
    private com.toedter.calendar.JDateChooser dataPagaCadAlun;
    private com.toedter.calendar.JDateChooser dataRecAlun;
    private javax.swing.JLabel emailAlun;
    private javax.swing.JTextField emailCadAlun;
    private javax.swing.JLabel foto;
    private javax.swing.JLabel fotoCadAlun;
    private javax.swing.JLabel nomeAlun;
    private javax.swing.JTextField nomeCadAlun;
    private javax.swing.JTextField nomeRecAlun;
    private javax.swing.JLabel nutriAlun;
    private javax.swing.JComboBox<String> nutriCadAlun;
    private javax.swing.JLabel pagaAlun;
    private javax.swing.JTextField pesquisarAlun;
    private javax.swing.JTextField precoRecAlun;
    private javax.swing.JLabel sexoAlun;
    private javax.swing.JTextField sexoCadAlun;
    private javax.swing.JLabel telefoneAlun;
    private javax.swing.JTextField telefoneCadAlun;
    // End of variables declaration//GEN-END:variables
}
