/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AdmRegGas;

import AdmAgenServ.*;
import AdmFuncion�rio.*;
import Principal.*;

/**
 *
 * @author GabrielFelipe
 */
public class OpRegistroGastos extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public OpRegistroGastos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VoltarRegGastos = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        TelaRegGas = new javax.swing.JTabbedPane();
        AbaRegGas = new javax.swing.JPanel();
        NomeRegGas = new javax.swing.JLabel();
        nomeRegGas = new javax.swing.JLabel();
        ObjRegGas = new javax.swing.JLabel();
        objRegGas = new javax.swing.JLabel();
        DataRegGas = new javax.swing.JLabel();
        dataRegGas = new javax.swing.JLabel();
        CpfRegGas = new javax.swing.JLabel();
        cpfRegGas = new javax.swing.JLabel();
        RealRegGas = new javax.swing.JLabel();
        realRegGas = new javax.swing.JLabel();
        CPFRealRegGas = new javax.swing.JLabel();
        cpfRealAgenServ = new javax.swing.JLabel();
        AbaCadRegGas = new javax.swing.JPanel();
        NomeCadRegGas = new javax.swing.JLabel();
        nomeCadRegGas = new javax.swing.JTextField();
        ObjCadRegGas = new javax.swing.JLabel();
        objCadRegGas = new javax.swing.JTextField();
        DataCadRegGas = new javax.swing.JLabel();
        dataCadRegGas = new com.toedter.calendar.JDateChooser();
        ValorCadRegGas = new javax.swing.JLabel();
        valorCadRegGas = new javax.swing.JTextField();
        RealCadRegGas = new javax.swing.JLabel();
        realCadRegGas = new javax.swing.JTextField();
        CPFCadRegGas = new javax.swing.JLabel();
        cpfCadRegGas = new javax.swing.JTextField();
        CadastrarRegGas = new javax.swing.JButton();
        EditarRegGas = new javax.swing.JButton();
        ExcluirRegGas = new javax.swing.JButton();
        TabelaPesquisaGastos = new javax.swing.JPanel();
        PesquisarRegGas = new javax.swing.JButton();
        pesquisarRegGas = new javax.swing.JTextField();
        ScrollTabelaRegGas = new javax.swing.JScrollPane();
        TabelaRegGas = new javax.swing.JTable();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(1000, 640));
        setName("Login"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1000, 640));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 640));
        getContentPane().setLayout(null);

        VoltarRegGastos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Voltar.png"))); // NOI18N
        VoltarRegGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarRegGastosActionPerformed(evt);
            }
        });
        getContentPane().add(VoltarRegGastos);
        VoltarRegGastos.setBounds(0, 0, 60, 40);

        Titulo.setFont(new java.awt.Font("Impact", 0, 30)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Administrador");
        getContentPane().add(Titulo);
        Titulo.setBounds(0, 10, 1000, 30);

        TelaRegGas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        AbaRegGas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        NomeRegGas.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        NomeRegGas.setText("Nome:");

        nomeRegGas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nomeRegGas.setText("Null");

        ObjRegGas.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        ObjRegGas.setText("Objetivo:");

        objRegGas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        objRegGas.setText("Null");

        DataRegGas.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        DataRegGas.setText("Data:");

        dataRegGas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        dataRegGas.setText("Null");

        CpfRegGas.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        CpfRegGas.setText("CPF:");

        cpfRegGas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cpfRegGas.setText("Null");

        RealRegGas.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        RealRegGas.setText("Realizador:");

        realRegGas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        realRegGas.setText("Null");

        CPFRealRegGas.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        CPFRealRegGas.setText("CPF:");

        cpfRealAgenServ.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cpfRealAgenServ.setText("Null");

        javax.swing.GroupLayout AbaRegGasLayout = new javax.swing.GroupLayout(AbaRegGas);
        AbaRegGas.setLayout(AbaRegGasLayout);
        AbaRegGasLayout.setHorizontalGroup(
            AbaRegGasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AbaRegGasLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(AbaRegGasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AbaRegGasLayout.createSequentialGroup()
                        .addComponent(ObjRegGas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(objRegGas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(AbaRegGasLayout.createSequentialGroup()
                        .addComponent(NomeRegGas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeRegGas, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(AbaRegGasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbaRegGasLayout.createSequentialGroup()
                        .addComponent(DataRegGas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataRegGas, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AbaRegGasLayout.createSequentialGroup()
                        .addComponent(CpfRegGas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpfRegGas, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AbaRegGasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbaRegGasLayout.createSequentialGroup()
                        .addComponent(RealRegGas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(realRegGas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AbaRegGasLayout.createSequentialGroup()
                        .addComponent(CPFRealRegGas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpfRealAgenServ, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        AbaRegGasLayout.setVerticalGroup(
            AbaRegGasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaRegGasLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(AbaRegGasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbaRegGasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RealRegGas)
                        .addComponent(realRegGas))
                    .addGroup(AbaRegGasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nomeRegGas)
                        .addComponent(DataRegGas)
                        .addComponent(dataRegGas))
                    .addGroup(AbaRegGasLayout.createSequentialGroup()
                        .addComponent(NomeRegGas)
                        .addGap(18, 18, 18)
                        .addGroup(AbaRegGasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ObjRegGas)
                            .addComponent(objRegGas)
                            .addComponent(CpfRegGas)
                            .addComponent(cpfRegGas)
                            .addComponent(CPFRealRegGas)
                            .addComponent(cpfRealAgenServ))))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        TelaRegGas.addTab("Gastos", AbaRegGas);

        AbaCadRegGas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        NomeCadRegGas.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        NomeCadRegGas.setText("Nome:");

        nomeCadRegGas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        ObjCadRegGas.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        ObjCadRegGas.setText("Objetivo:");

        objCadRegGas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        DataCadRegGas.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        DataCadRegGas.setText("Data:");

        dataCadRegGas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        ValorCadRegGas.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        ValorCadRegGas.setText("Valor:");

        valorCadRegGas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        RealCadRegGas.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        RealCadRegGas.setText("Realizador:");

        realCadRegGas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        CPFCadRegGas.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        CPFCadRegGas.setText("CPF:");

        cpfCadRegGas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        CadastrarRegGas.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        CadastrarRegGas.setText("Cadastrar");

        EditarRegGas.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        EditarRegGas.setText("Editar");

        ExcluirRegGas.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        ExcluirRegGas.setText("Excluir");

        javax.swing.GroupLayout AbaCadRegGasLayout = new javax.swing.GroupLayout(AbaCadRegGas);
        AbaCadRegGas.setLayout(AbaCadRegGasLayout);
        AbaCadRegGasLayout.setHorizontalGroup(
            AbaCadRegGasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaCadRegGasLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(AbaCadRegGasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbaCadRegGasLayout.createSequentialGroup()
                        .addGroup(AbaCadRegGasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AbaCadRegGasLayout.createSequentialGroup()
                                .addComponent(ObjCadRegGas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(objCadRegGas))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AbaCadRegGasLayout.createSequentialGroup()
                                .addComponent(NomeCadRegGas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomeCadRegGas, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(AbaCadRegGasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AbaCadRegGasLayout.createSequentialGroup()
                                .addComponent(DataCadRegGas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dataCadRegGas, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AbaCadRegGasLayout.createSequentialGroup()
                                .addComponent(ValorCadRegGas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valorCadRegGas, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(AbaCadRegGasLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(AbaCadRegGasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RealCadRegGas)
                            .addComponent(CPFCadRegGas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AbaCadRegGasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cpfCadRegGas)
                            .addComponent(realCadRegGas, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(AbaCadRegGasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ExcluirRegGas, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CadastrarRegGas)
                    .addComponent(EditarRegGas, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103))
        );
        AbaCadRegGasLayout.setVerticalGroup(
            AbaCadRegGasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AbaCadRegGasLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(AbaCadRegGasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbaCadRegGasLayout.createSequentialGroup()
                        .addComponent(CadastrarRegGas)
                        .addGap(18, 18, 18)
                        .addComponent(EditarRegGas))
                    .addGroup(AbaCadRegGasLayout.createSequentialGroup()
                        .addGroup(AbaCadRegGasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataCadRegGas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AbaCadRegGasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(NomeCadRegGas)
                                .addComponent(nomeCadRegGas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DataCadRegGas)))
                        .addGap(10, 10, 10)
                        .addGroup(AbaCadRegGasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ObjCadRegGas)
                            .addComponent(objCadRegGas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ValorCadRegGas)
                            .addComponent(valorCadRegGas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(AbaCadRegGasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ExcluirRegGas)
                    .addGroup(AbaCadRegGasLayout.createSequentialGroup()
                        .addGroup(AbaCadRegGasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RealCadRegGas)
                            .addComponent(realCadRegGas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AbaCadRegGasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CPFCadRegGas)
                            .addComponent(cpfCadRegGas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29))
        );

        TelaRegGas.addTab("Controle", AbaCadRegGas);

        getContentPane().add(TelaRegGas);
        TelaRegGas.setBounds(50, 40, 900, 300);

        TabelaPesquisaGastos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        PesquisarRegGas.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        PesquisarRegGas.setText("Pesquisar");

        pesquisarRegGas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        pesquisarRegGas.setPreferredSize(new java.awt.Dimension(74, 32));

        TabelaRegGas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TabelaRegGas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TabelaRegGas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Serviço", "Data"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaRegGas.setToolTipText("");
        TabelaRegGas.setAlignmentX(1.0F);
        TabelaRegGas.setAlignmentY(1.0F);
        TabelaRegGas.setRowHeight(28);
        ScrollTabelaRegGas.setViewportView(TabelaRegGas);

        javax.swing.GroupLayout TabelaPesquisaGastosLayout = new javax.swing.GroupLayout(TabelaPesquisaGastos);
        TabelaPesquisaGastos.setLayout(TabelaPesquisaGastosLayout);
        TabelaPesquisaGastosLayout.setHorizontalGroup(
            TabelaPesquisaGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabelaPesquisaGastosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PesquisarRegGas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pesquisarRegGas, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TabelaPesquisaGastosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ScrollTabelaRegGas, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        TabelaPesquisaGastosLayout.setVerticalGroup(
            TabelaPesquisaGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabelaPesquisaGastosLayout.createSequentialGroup()
                .addGroup(TabelaPesquisaGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PesquisarRegGas)
                    .addComponent(pesquisarRegGas, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(ScrollTabelaRegGas, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(TabelaPesquisaGastos);
        TabelaPesquisaGastos.setBounds(50, 340, 900, 240);

        Background.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        Background.setPreferredSize(new java.awt.Dimension(1000, 570));
        getContentPane().add(Background);
        Background.setBounds(0, 0, 1000, 640);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarRegGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarRegGastosActionPerformed
        // Botão Voltar

        AdmSelecao AS = new AdmSelecao();
        AS.setVisible(true);
        dispose();
    }//GEN-LAST:event_VoltarRegGastosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpRegistroGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpRegistroGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpRegistroGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpRegistroGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpRegistroGastos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AbaCadRegGas;
    private javax.swing.JPanel AbaRegGas;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel CPFCadRegGas;
    private javax.swing.JLabel CPFRealRegGas;
    private javax.swing.JButton CadastrarRegGas;
    private javax.swing.JLabel CpfRegGas;
    private javax.swing.JLabel DataCadRegGas;
    private javax.swing.JLabel DataRegGas;
    private javax.swing.JButton EditarRegGas;
    private javax.swing.JButton ExcluirRegGas;
    private javax.swing.JLabel NomeCadRegGas;
    private javax.swing.JLabel NomeRegGas;
    private javax.swing.JLabel ObjCadRegGas;
    private javax.swing.JLabel ObjRegGas;
    private javax.swing.JButton PesquisarRegGas;
    private javax.swing.JLabel RealCadRegGas;
    private javax.swing.JLabel RealRegGas;
    private javax.swing.JScrollPane ScrollTabelaRegGas;
    private javax.swing.JPanel TabelaPesquisaGastos;
    private javax.swing.JTable TabelaRegGas;
    private javax.swing.JTabbedPane TelaRegGas;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel ValorCadRegGas;
    private javax.swing.JButton VoltarRegGastos;
    private javax.swing.JTextField cpfCadRegGas;
    private javax.swing.JLabel cpfRealAgenServ;
    private javax.swing.JLabel cpfRegGas;
    private com.toedter.calendar.JDateChooser dataCadRegGas;
    private javax.swing.JLabel dataRegGas;
    private javax.swing.JTextField nomeCadRegGas;
    private javax.swing.JLabel nomeRegGas;
    private javax.swing.JTextField objCadRegGas;
    private javax.swing.JLabel objRegGas;
    private javax.swing.JTextField pesquisarRegGas;
    private javax.swing.JTextField realCadRegGas;
    private javax.swing.JLabel realRegGas;
    private javax.swing.JTextField valorCadRegGas;
    // End of variables declaration//GEN-END:variables
}
