/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import AdmEquipamentos.OpEquipamentos;
import AdmFuncion�rio.OpFuncionarios;
import AdmAluno.OpAlunos;
import AdmAgenServ.OpAgendamentoServico;
import AdmRegGas.OpRegistroGastos;
import AdmTurmas.OpTurma;
import Principal.*;

/**
 *
 * @author GabrielFelipe
 */
public class AdmSelecao extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogimm
     */
    public AdmSelecao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelSelecao = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        OpFunc = new javax.swing.JButton();
        OpAlun = new javax.swing.JButton();
        OpTurm = new javax.swing.JButton();
        OpEquip = new javax.swing.JButton();
        OpAgenServ = new javax.swing.JButton();
        OpRegGas = new javax.swing.JButton();
        Sair = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 640));
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(null);

        PainelSelecao.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Titulo.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Seleção");

        OpFunc.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        OpFunc.setText("Funcionários");
        OpFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpFuncActionPerformed(evt);
            }
        });

        OpAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        OpAlun.setText("Alunos");
        OpAlun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpAlunActionPerformed(evt);
            }
        });

        OpTurm.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        OpTurm.setText("Turmas");
        OpTurm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpTurmActionPerformed(evt);
            }
        });

        OpEquip.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        OpEquip.setText("Equipamentos");
        OpEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpEquipActionPerformed(evt);
            }
        });

        OpAgenServ.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        OpAgenServ.setText("Agendamento de Serviços");
        OpAgenServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpAgenServActionPerformed(evt);
            }
        });

        OpRegGas.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        OpRegGas.setText("Registro de Gastos");
        OpRegGas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpRegGasActionPerformed(evt);
            }
        });

        Sair.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelSelecaoLayout = new javax.swing.GroupLayout(PainelSelecao);
        PainelSelecao.setLayout(PainelSelecaoLayout);
        PainelSelecaoLayout.setHorizontalGroup(
            PainelSelecaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Titulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelSelecaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PainelSelecaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelSelecaoLayout.createSequentialGroup()
                        .addComponent(Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelSelecaoLayout.createSequentialGroup()
                        .addGroup(PainelSelecaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(OpAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OpFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OpTurm, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OpEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OpAgenServ, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OpRegGas, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))))
        );
        PainelSelecaoLayout.setVerticalGroup(
            PainelSelecaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelSelecaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(OpFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(OpAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(OpTurm, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(OpEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(OpAgenServ, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(OpRegGas, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(PainelSelecao);
        PainelSelecao.setBounds(370, 60, 280, 510);

        Background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Background.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        Background.setPreferredSize(new java.awt.Dimension(1000, 570));
        getContentPane().add(Background);
        Background.setBounds(0, 0, 1000, 640);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        // Click Botão de Sair

        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_SairActionPerformed

    private void OpEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpEquipActionPerformed
        // Botão Equipamentos

        OpEquipamentos OE = new OpEquipamentos();
        OE.setVisible(true);
        dispose();
    }//GEN-LAST:event_OpEquipActionPerformed

    private void OpFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpFuncActionPerformed
        // Botão Funcionário

        OpFuncionarios OF = new OpFuncionarios();
        OF.setVisible(true);
        dispose();
    }//GEN-LAST:event_OpFuncActionPerformed

    private void OpAlunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpAlunActionPerformed
        // Botão Aluno

        OpAlunos OA = new OpAlunos();
        OA.setVisible(true);
        dispose();
    }//GEN-LAST:event_OpAlunActionPerformed

    private void OpTurmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpTurmActionPerformed
        // Botão Turma

        OpTurma OT = new OpTurma();
        OT.setVisible(true);
        dispose();
    }//GEN-LAST:event_OpTurmActionPerformed

    private void OpAgenServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpAgenServActionPerformed
        // Botão Agendamento de Serviços

        OpAgendamentoServico OAS = new OpAgendamentoServico();
        OAS.setVisible(true);
        dispose();
    }//GEN-LAST:event_OpAgenServActionPerformed

    private void OpRegGasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpRegGasActionPerformed
        // Botão Registro de Gastos

        OpRegistroGastos ORG = new OpRegistroGastos();
        ORG.setVisible(true);
        dispose();
    }//GEN-LAST:event_OpRegGasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdmSelecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdmSelecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdmSelecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdmSelecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdmSelecao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton OpAgenServ;
    private javax.swing.JButton OpAlun;
    private javax.swing.JButton OpEquip;
    private javax.swing.JButton OpFunc;
    private javax.swing.JButton OpRegGas;
    private javax.swing.JButton OpTurm;
    private javax.swing.JPanel PainelSelecao;
    private javax.swing.JButton Sair;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables
}
