/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AdmFuncion�rio;

import Teste.Funcionario;
import Principal.*;
import Teste.BancoFalso;
import java.io.File;
import java.sql.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GabrielFelipe
 */
public class OpFuncionarios extends javax.swing.JFrame {

    BancoFalso mestre = new BancoFalso();
    public static int indice = -1;

    /**
     * Creates new form NewJFrame
     */
    public OpFuncionarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        VoltarFunc = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        TelaFunc = new javax.swing.JTabbedPane();
        AbaFunc = new javax.swing.JPanel();
        fotoFunc = new javax.swing.JLabel();
        TelefoneFunc = new javax.swing.JLabel();
        telefoneFunc = new javax.swing.JLabel();
        EmailFunc = new javax.swing.JLabel();
        emailFunc = new javax.swing.JLabel();
        NomeFunc = new javax.swing.JLabel();
        nomeFunc = new javax.swing.JLabel();
        CPFFunc = new javax.swing.JLabel();
        cpfFunc = new javax.swing.JLabel();
        CargoFunc = new javax.swing.JLabel();
        cargoFunc = new javax.swing.JLabel();
        SalarioFunc = new javax.swing.JLabel();
        salarioFunc = new javax.swing.JLabel();
        DataNascFunc = new javax.swing.JLabel();
        dataNascFunc = new javax.swing.JLabel();
        AbaCadFunc = new javax.swing.JPanel();
        fotoCadFunc = new javax.swing.JLabel();
        AdicionarFotoFunc = new javax.swing.JButton();
        NomeCadFunc = new javax.swing.JLabel();
        nomeCadFunc = new javax.swing.JTextField();
        CPFCadFunc = new javax.swing.JLabel();
        cpfCadFunc = new javax.swing.JTextField();
        SalarioCadFunc = new javax.swing.JLabel();
        salarioCadFunc = new javax.swing.JTextField();
        CargoCadFunc = new javax.swing.JLabel();
        cargoCadFunc = new javax.swing.JComboBox<>();
        DataNascCadFunc = new javax.swing.JLabel();
        dataNascCadFunc = new com.toedter.calendar.JDateChooser();
        TelefoneCadFunc = new javax.swing.JLabel();
        telefoneCadFunc = new javax.swing.JTextField();
        EmailCadFunc = new javax.swing.JLabel();
        emailCadFunc = new javax.swing.JTextField();
        CadastrarFunc = new javax.swing.JButton();
        EditarFunc = new javax.swing.JButton();
        ExcluirFunc = new javax.swing.JButton();
        AbaReciboFunc = new javax.swing.JPanel();
        Texto1 = new javax.swing.JLabel();
        nomeEmpresaRecFunc = new javax.swing.JTextField();
        Texto2 = new javax.swing.JLabel();
        salarioRecFunc = new javax.swing.JTextField();
        Texto3 = new javax.swing.JLabel();
        cargoRecFunc = new javax.swing.JTextField();
        DataRecFunc = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        Assinatura1RecFunc = new javax.swing.JLabel();
        Assinatura2RecFunc = new javax.swing.JLabel();
        SalvarRecFunc = new javax.swing.JButton();
        TabelaPesquisaFunc = new javax.swing.JPanel();
        PesquisarFunc = new javax.swing.JButton();
        pesquisarFunc = new javax.swing.JTextField();
        ScrollTabelaFunc = new javax.swing.JScrollPane();
        TabelaFunc = new javax.swing.JTable();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(1000, 640));
        setName("Login"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 640));
        getContentPane().setLayout(null);

        VoltarFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Voltar.png"))); // NOI18N
        VoltarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarFuncActionPerformed(evt);
            }
        });
        getContentPane().add(VoltarFunc);
        VoltarFunc.setBounds(0, 0, 60, 40);

        Titulo.setFont(new java.awt.Font("Impact", 0, 30)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Administrador");
        getContentPane().add(Titulo);
        Titulo.setBounds(0, 10, 1000, 30);

        TelaFunc.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        AbaFunc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        fotoFunc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TelefoneFunc.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        TelefoneFunc.setText("Telefone:");

        telefoneFunc.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        telefoneFunc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        telefoneFunc.setText("Null");
        telefoneFunc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        EmailFunc.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        EmailFunc.setText("Email:");

        emailFunc.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        emailFunc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emailFunc.setText("Null");
        emailFunc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        NomeFunc.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        NomeFunc.setText("Nome:");

        nomeFunc.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nomeFunc.setText("Null");

        CPFFunc.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        CPFFunc.setText("CPF:");

        cpfFunc.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cpfFunc.setText("Null");

        CargoFunc.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        CargoFunc.setText("Cargo:");

        cargoFunc.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cargoFunc.setText("Null");

        SalarioFunc.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        SalarioFunc.setText("Salário");

        salarioFunc.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        salarioFunc.setText("Null");

        DataNascFunc.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        DataNascFunc.setText("Data de Nasc:");

        dataNascFunc.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        dataNascFunc.setText("Null");

        javax.swing.GroupLayout AbaFuncLayout = new javax.swing.GroupLayout(AbaFunc);
        AbaFunc.setLayout(AbaFuncLayout);
        AbaFuncLayout.setHorizontalGroup(
            AbaFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaFuncLayout.createSequentialGroup()
                .addGroup(AbaFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbaFuncLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(fotoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AbaFuncLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(AbaFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AbaFuncLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(TelefoneFunc)
                                .addGap(35, 35, 35))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AbaFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(AbaFuncLayout.createSequentialGroup()
                                    .addGap(57, 57, 57)
                                    .addComponent(EmailFunc)
                                    .addGap(34, 34, 34))
                                .addComponent(emailFunc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(telefoneFunc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)))
                .addGroup(AbaFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbaFuncLayout.createSequentialGroup()
                        .addComponent(NomeFunc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomeFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AbaFuncLayout.createSequentialGroup()
                        .addGroup(AbaFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AbaFuncLayout.createSequentialGroup()
                                .addComponent(CPFFunc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cpfFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AbaFuncLayout.createSequentialGroup()
                                .addComponent(CargoFunc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cargoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AbaFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AbaFuncLayout.createSequentialGroup()
                                .addComponent(DataNascFunc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dataNascFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AbaFuncLayout.createSequentialGroup()
                                .addComponent(SalarioFunc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(salarioFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AbaFuncLayout.setVerticalGroup(
            AbaFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AbaFuncLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(AbaFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AbaFuncLayout.createSequentialGroup()
                        .addComponent(fotoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(TelefoneFunc))
                    .addGroup(AbaFuncLayout.createSequentialGroup()
                        .addGroup(AbaFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NomeFunc)
                            .addComponent(nomeFunc))
                        .addGap(18, 18, 18)
                        .addGroup(AbaFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AbaFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(CPFFunc)
                                .addComponent(cpfFunc))
                            .addGroup(AbaFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SalarioFunc)
                                .addComponent(salarioFunc)))
                        .addGap(18, 18, 18)
                        .addGroup(AbaFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CargoFunc)
                            .addComponent(cargoFunc)
                            .addComponent(DataNascFunc)
                            .addComponent(dataNascFunc))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telefoneFunc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EmailFunc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailFunc)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        TelaFunc.addTab("Funcionários", AbaFunc);

        AbaCadFunc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        fotoCadFunc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        AdicionarFotoFunc.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        AdicionarFotoFunc.setText("Adicionar");
        AdicionarFotoFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionarFotoFuncActionPerformed(evt);
            }
        });

        NomeCadFunc.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        NomeCadFunc.setText("Nome:");

        nomeCadFunc.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nomeCadFunc.setPreferredSize(new java.awt.Dimension(74, 32));

        CPFCadFunc.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        CPFCadFunc.setText("CPF:");

        cpfCadFunc.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cpfCadFunc.setPreferredSize(new java.awt.Dimension(74, 32));

        SalarioCadFunc.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        SalarioCadFunc.setText("Salário:");

        salarioCadFunc.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        salarioCadFunc.setPreferredSize(new java.awt.Dimension(74, 32));

        CargoCadFunc.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        CargoCadFunc.setText("Cargo:");

        cargoCadFunc.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cargoCadFunc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Instrutor", "Nutricionista" }));

        DataNascCadFunc.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        DataNascCadFunc.setText("Data de Nasc:");

        dataNascCadFunc.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        TelefoneCadFunc.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        TelefoneCadFunc.setText("Telefone:");

        telefoneCadFunc.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        telefoneCadFunc.setPreferredSize(new java.awt.Dimension(74, 32));

        EmailCadFunc.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        EmailCadFunc.setText("Email:");

        emailCadFunc.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        emailCadFunc.setPreferredSize(new java.awt.Dimension(74, 32));

        CadastrarFunc.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        CadastrarFunc.setText("Cadastrar");
        CadastrarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarFuncActionPerformed(evt);
            }
        });

        EditarFunc.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        EditarFunc.setText("Editar");
        EditarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarFuncActionPerformed(evt);
            }
        });

        ExcluirFunc.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        ExcluirFunc.setText("Excluir");
        ExcluirFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirFuncActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AbaCadFuncLayout = new javax.swing.GroupLayout(AbaCadFunc);
        AbaCadFunc.setLayout(AbaCadFuncLayout);
        AbaCadFuncLayout.setHorizontalGroup(
            AbaCadFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaCadFuncLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(AbaCadFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AdicionarFotoFunc)
                    .addGroup(AbaCadFuncLayout.createSequentialGroup()
                        .addComponent(fotoCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(AbaCadFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(AbaCadFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(AbaCadFuncLayout.createSequentialGroup()
                                    .addComponent(CPFCadFunc)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cpfCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(SalarioCadFunc)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(salarioCadFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(AbaCadFuncLayout.createSequentialGroup()
                                    .addComponent(NomeCadFunc)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(nomeCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(AbaCadFuncLayout.createSequentialGroup()
                                    .addComponent(TelefoneCadFunc)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(telefoneCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(EmailCadFunc)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(emailCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(AbaCadFuncLayout.createSequentialGroup()
                                .addComponent(CargoCadFunc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cargoCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DataNascCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dataNascCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(AbaCadFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ExcluirFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CadastrarFunc)
                    .addComponent(EditarFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );
        AbaCadFuncLayout.setVerticalGroup(
            AbaCadFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaCadFuncLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(AbaCadFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbaCadFuncLayout.createSequentialGroup()
                        .addComponent(fotoCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AdicionarFotoFunc))
                    .addGroup(AbaCadFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AbaCadFuncLayout.createSequentialGroup()
                            .addGroup(AbaCadFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(NomeCadFunc)
                                .addComponent(nomeCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(AbaCadFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(AbaCadFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CPFCadFunc)
                                    .addComponent(cpfCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(AbaCadFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(salarioCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SalarioCadFunc)))
                            .addGap(18, 18, 18)
                            .addGroup(AbaCadFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(AbaCadFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CargoCadFunc)
                                    .addComponent(DataNascCadFunc)
                                    .addComponent(cargoCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(dataNascCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(17, 17, 17)
                            .addGroup(AbaCadFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TelefoneCadFunc)
                                .addComponent(telefoneCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(EmailCadFunc)
                                .addComponent(emailCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AbaCadFuncLayout.createSequentialGroup()
                            .addComponent(CadastrarFunc)
                            .addGap(18, 18, 18)
                            .addComponent(EditarFunc)
                            .addGap(18, 18, 18)
                            .addComponent(ExcluirFunc)
                            .addGap(8, 8, 8))))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        TelaFunc.addTab("Controle", AbaCadFunc);

        AbaReciboFunc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Texto1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Texto1.setText("Recebi do Sr/Empresa ");

        nomeEmpresaRecFunc.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nomeEmpresaRecFunc.setPreferredSize(new java.awt.Dimension(74, 32));

        Texto2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Texto2.setText("a quantia de ");

        salarioRecFunc.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        salarioRecFunc.setPreferredSize(new java.awt.Dimension(74, 32));

        Texto3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Texto3.setText("correspondente ao pagamento mensal como ");

        cargoRecFunc.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cargoRecFunc.setPreferredSize(new java.awt.Dimension(74, 32));

        DataRecFunc.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        DataRecFunc.setText("referente a data");

        jDateChooser2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        Assinatura1RecFunc.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        Assinatura1RecFunc.setText("_________________________________________________");

        Assinatura2RecFunc.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Assinatura2RecFunc.setText("Assinatura");

        SalvarRecFunc.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        SalvarRecFunc.setText("Salvar e Imprimir");
        SalvarRecFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarRecFuncActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AbaReciboFuncLayout = new javax.swing.GroupLayout(AbaReciboFunc);
        AbaReciboFunc.setLayout(AbaReciboFuncLayout);
        AbaReciboFuncLayout.setHorizontalGroup(
            AbaReciboFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaReciboFuncLayout.createSequentialGroup()
                .addGroup(AbaReciboFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbaReciboFuncLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(AbaReciboFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AbaReciboFuncLayout.createSequentialGroup()
                                .addComponent(Texto1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomeEmpresaRecFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Texto2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(salarioRecFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AbaReciboFuncLayout.createSequentialGroup()
                                .addComponent(Texto3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cargoRecFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DataRecFunc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(AbaReciboFuncLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addGroup(AbaReciboFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Assinatura1RecFunc)
                            .addGroup(AbaReciboFuncLayout.createSequentialGroup()
                                .addGap(197, 197, 197)
                                .addComponent(Assinatura2RecFunc))))
                    .addGroup(AbaReciboFuncLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SalvarRecFunc)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        AbaReciboFuncLayout.setVerticalGroup(
            AbaReciboFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaReciboFuncLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SalvarRecFunc)
                .addGap(31, 31, 31)
                .addGroup(AbaReciboFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Texto1)
                    .addComponent(nomeEmpresaRecFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Texto2)
                    .addComponent(salarioRecFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AbaReciboFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbaReciboFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Texto3)
                        .addComponent(cargoRecFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DataRecFunc))
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(Assinatura1RecFunc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Assinatura2RecFunc)
                .addGap(194, 194, 194))
        );

        TelaFunc.addTab("Recibo", AbaReciboFunc);

        getContentPane().add(TelaFunc);
        TelaFunc.setBounds(50, 40, 900, 300);

        TabelaPesquisaFunc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        PesquisarFunc.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        PesquisarFunc.setText("Pesquisar");
        PesquisarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarFuncActionPerformed(evt);
            }
        });

        pesquisarFunc.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        pesquisarFunc.setPreferredSize(new java.awt.Dimension(74, 32));

        TabelaFunc.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TabelaFunc.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TabelaFunc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "CPF", "Salário"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaFunc.setToolTipText("");
        TabelaFunc.setAlignmentX(1.0F);
        TabelaFunc.setAlignmentY(1.0F);
        TabelaFunc.setRowHeight(28);
        ScrollTabelaFunc.setViewportView(TabelaFunc);

        javax.swing.GroupLayout TabelaPesquisaFuncLayout = new javax.swing.GroupLayout(TabelaPesquisaFunc);
        TabelaPesquisaFunc.setLayout(TabelaPesquisaFuncLayout);
        TabelaPesquisaFuncLayout.setHorizontalGroup(
            TabelaPesquisaFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabelaPesquisaFuncLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PesquisarFunc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pesquisarFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TabelaPesquisaFuncLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ScrollTabelaFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        TabelaPesquisaFuncLayout.setVerticalGroup(
            TabelaPesquisaFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabelaPesquisaFuncLayout.createSequentialGroup()
                .addGroup(TabelaPesquisaFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PesquisarFunc)
                    .addComponent(pesquisarFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(ScrollTabelaFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(TabelaPesquisaFunc);
        TabelaPesquisaFunc.setBounds(50, 340, 900, 240);

        Background.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        Background.setPreferredSize(new java.awt.Dimension(1000, 570));
        getContentPane().add(Background);
        Background.setBounds(0, 0, 1000, 640);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SalvarRecFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarRecFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalvarRecFuncActionPerformed

    private void VoltarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarFuncActionPerformed
        // Botão Voltar

        AdmSelecao AS = new AdmSelecao();
        AS.setVisible(true);
        dispose();
    }//GEN-LAST:event_VoltarFuncActionPerformed

    private void PesquisarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarFuncActionPerformed
        // Botão Pesquisar Funcionário

        DefaultTableModel TF = (DefaultTableModel) TabelaFunc.getModel();
        TF.setNumRows(0);

        for (int i = 0; i < mestre.funcionarios.size(); i++) {

            System.out.println(mestre.funcionarios.get(i).toString());

            if (pesquisarFunc.getText().equalsIgnoreCase("[aA-zZ]")) {
                JOptionPane.showMessageDialog(null, "Digite um CPF!!!");
            }

            if (mestre.funcionarios.get(i).cpf.equals(pesquisarFunc.getText())) {
                TF.setNumRows(0);

                TF.addRow(new Object[]{
                    mestre.funcionarios.get(i).nome,
                    mestre.funcionarios.get(i).cpf,
                    mestre.funcionarios.get(i).salario,});

                //Funcionário
                nomeFunc.setText(mestre.funcionarios.get(i).nome);
                cpfFunc.setText(mestre.funcionarios.get(i).cpf);
                cargoFunc.setText(mestre.funcionarios.get(i).cargo);
                salarioFunc.setText(String.valueOf(mestre.funcionarios.get(i).salario));
                dataNascFunc.setText(mestre.funcionarios.get(i).dataNasc);
                telefoneFunc.setText(mestre.funcionarios.get(i).telefone);
                emailFunc.setText(mestre.funcionarios.get(i).email);

                fotoFunc.setIcon(mestre.funcionarios.get(i).foto);

                //Controle
                nomeCadFunc.setText(mestre.funcionarios.get(i).nome);
                cpfCadFunc.setText(mestre.funcionarios.get(i).cpf);
                cargoCadFunc.setSelectedItem(mestre.funcionarios.get(i).cargo);
                salarioCadFunc.setText(String.valueOf(mestre.funcionarios.get(i).salario));
                dataNascCadFunc.setDateFormatString(mestre.funcionarios.get(i).dataNasc);
                telefoneCadFunc.setText(mestre.funcionarios.get(i).telefone);
                emailCadFunc.setText(mestre.funcionarios.get(i).email);

                fotoCadFunc.setIcon(new ImageIcon(getClass().getResource("/Imagens/Perfil.png")));
                fotoCadFunc.setIcon((Icon) mestre.funcionarios.get(i).foto);

                //Recibo
                nomeEmpresaRecFunc.setText("Empresa Pikorosa de Exercicios");
                salarioRecFunc.setText(String.valueOf(mestre.funcionarios.get(i).salario));
                cargoRecFunc.setText(mestre.funcionarios.get(i).cargo);
            }

            if (pesquisarFunc.getText().equalsIgnoreCase("")) {
                TF.addRow(new Object[]{
                    mestre.funcionarios.get(i).nome,
                    mestre.funcionarios.get(i).cpf,
                    mestre.funcionarios.get(i).salario,});
            }
        }

    }//GEN-LAST:event_PesquisarFuncActionPerformed

    private void CadastrarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarFuncActionPerformed
        // Botão Cadastrar
        try {
            Funcionario F = new Funcionario();

            F.nome = nomeCadFunc.getText();
            F.cpf = cpfCadFunc.getText();
            F.cargo = (String) cargoCadFunc.getSelectedItem();
            F.salario = Double.parseDouble(salarioCadFunc.getText());
            F.dataNasc = dataNascCadFunc.getDateFormatString();
            F.telefone = telefoneCadFunc.getText();
            F.email = emailCadFunc.getText();
            F.foto = fotoCadFunc.getIcon();

            mestre.funcionarios.add(F);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Preencha Todos os Campos Corretamente!!!");
        }

    }//GEN-LAST:event_CadastrarFuncActionPerformed

    private void AdicionarFotoFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionarFotoFuncActionPerformed
        // Adicionar Foto no Cadastro

        String foto;
        jFileChooser1.showOpenDialog(this);
        File arquivo = jFileChooser1.getSelectedFile();

        if (arquivo != null) {
            foto = (arquivo.getPath());
            fotoCadFunc.setIcon(new ImageIcon(foto));
            foto = (fotoCadFunc.getIcon().toString());

        } else {
            fotoCadFunc.setIcon(new ImageIcon(getClass().getResource("/Imagens/Perfil.png")));
            foto = (fotoCadFunc.getIcon().toString());
            System.out.println("else:" + foto);
        }

    }//GEN-LAST:event_AdicionarFotoFuncActionPerformed

    private void ExcluirFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirFuncActionPerformed
        // Botão Excluir Funcionario

        indice = TabelaFunc.getSelectedRow();

        if (indice >= 0) {
            ExcFuncAlerta EFA = new ExcFuncAlerta();
            EFA.setVisible(true);
        } else {

            JOptionPane.showMessageDialog(null, "Selecione o Funcionário na Tabela!!!");
        }

    }//GEN-LAST:event_ExcluirFuncActionPerformed

    private void EditarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarFuncActionPerformed
        // Botão Editar Funcionario

        try {

            indice = TabelaFunc.getSelectedRow();

            if (indice >= 0 && !cpfCadFunc.getText().isEmpty()) {
                mestre.funcionarios.get(indice).nome = nomeCadFunc.getText();
                mestre.funcionarios.get(indice).cpf = cpfCadFunc.getText();
                mestre.funcionarios.get(indice).cargo = (String) cargoCadFunc.getSelectedItem();
                mestre.funcionarios.get(indice).salario = Double.parseDouble(salarioCadFunc.getText());
                mestre.funcionarios.get(indice).dataNasc = dataNascCadFunc.getDateFormatString();
                mestre.funcionarios.get(indice).telefone = telefoneCadFunc.getText();
                mestre.funcionarios.get(indice).email = emailCadFunc.getText();
                mestre.funcionarios.get(indice).foto = fotoCadFunc.getIcon();

                JOptionPane.showMessageDialog(null, "Funcionário Editado com Sucesso!!!");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Selecione o Funcionário na Tabela e Preencha Todos os Campos Corretamente!!!");
        }
    }//GEN-LAST:event_EditarFuncActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpFuncionarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AbaCadFunc;
    private javax.swing.JPanel AbaFunc;
    private javax.swing.JPanel AbaReciboFunc;
    private javax.swing.JButton AdicionarFotoFunc;
    private javax.swing.JLabel Assinatura1RecFunc;
    private javax.swing.JLabel Assinatura2RecFunc;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel CPFCadFunc;
    private javax.swing.JLabel CPFFunc;
    private javax.swing.JButton CadastrarFunc;
    private javax.swing.JLabel CargoCadFunc;
    private javax.swing.JLabel CargoFunc;
    private javax.swing.JLabel DataNascCadFunc;
    private javax.swing.JLabel DataNascFunc;
    private javax.swing.JLabel DataRecFunc;
    private javax.swing.JButton EditarFunc;
    private javax.swing.JLabel EmailCadFunc;
    private javax.swing.JLabel EmailFunc;
    private javax.swing.JButton ExcluirFunc;
    private javax.swing.JLabel NomeCadFunc;
    private javax.swing.JLabel NomeFunc;
    private javax.swing.JButton PesquisarFunc;
    private javax.swing.JLabel SalarioCadFunc;
    private javax.swing.JLabel SalarioFunc;
    private javax.swing.JButton SalvarRecFunc;
    private javax.swing.JScrollPane ScrollTabelaFunc;
    private javax.swing.JTable TabelaFunc;
    private javax.swing.JPanel TabelaPesquisaFunc;
    private javax.swing.JTabbedPane TelaFunc;
    private javax.swing.JLabel TelefoneCadFunc;
    private javax.swing.JLabel TelefoneFunc;
    private javax.swing.JLabel Texto1;
    private javax.swing.JLabel Texto2;
    private javax.swing.JLabel Texto3;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton VoltarFunc;
    private javax.swing.JComboBox<String> cargoCadFunc;
    private javax.swing.JLabel cargoFunc;
    private javax.swing.JTextField cargoRecFunc;
    private javax.swing.JTextField cpfCadFunc;
    private javax.swing.JLabel cpfFunc;
    private com.toedter.calendar.JDateChooser dataNascCadFunc;
    private javax.swing.JLabel dataNascFunc;
    private javax.swing.JTextField emailCadFunc;
    private javax.swing.JLabel emailFunc;
    private javax.swing.JLabel fotoCadFunc;
    private javax.swing.JLabel fotoFunc;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JTextField nomeCadFunc;
    private javax.swing.JTextField nomeEmpresaRecFunc;
    private javax.swing.JLabel nomeFunc;
    private javax.swing.JTextField pesquisarFunc;
    private javax.swing.JTextField salarioCadFunc;
    private javax.swing.JLabel salarioFunc;
    private javax.swing.JTextField salarioRecFunc;
    private javax.swing.JTextField telefoneCadFunc;
    private javax.swing.JLabel telefoneFunc;
    // End of variables declaration//GEN-END:variables
}
