/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AdmEquipamentos;

import AdmAluno.*;
import AdmFuncion�rio.*;
import Principal.*;

/**
 *
 * @author GabrielFelipe
 */
public class OpEquipamentos extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public OpEquipamentos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VoltarEquip = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        TelaEquip = new javax.swing.JTabbedPane();
        AbaEquip = new javax.swing.JPanel();
        NomeEquip = new javax.swing.JLabel();
        nomeEquip = new javax.swing.JLabel();
        IDEquip = new javax.swing.JLabel();
        idEquip = new javax.swing.JLabel();
        MarcaEquip = new javax.swing.JLabel();
        marcaEquip = new javax.swing.JLabel();
        ManuEquip = new javax.swing.JLabel();
        manuEquip = new javax.swing.JLabel();
        StatusEquip = new javax.swing.JLabel();
        statusEquip = new javax.swing.JLabel();
        FabricanteEquip = new javax.swing.JLabel();
        fabricanteEquip = new javax.swing.JLabel();
        TelefoneEquip = new javax.swing.JLabel();
        telefoneEquip = new javax.swing.JLabel();
        EmailEquip = new javax.swing.JLabel();
        emailEquip = new javax.swing.JLabel();
        AbaCadEquip = new javax.swing.JPanel();
        NomeCadEquip = new javax.swing.JLabel();
        nomeCadEquip = new javax.swing.JTextField();
        IDCadEquip = new javax.swing.JLabel();
        idCadEquip = new javax.swing.JTextField();
        MarcaCadEquip = new javax.swing.JLabel();
        marcaCadEquip = new javax.swing.JTextField();
        ManuCadEquip = new javax.swing.JLabel();
        manuCadEquip = new com.toedter.calendar.JDateChooser();
        StatusCadEquip = new javax.swing.JLabel();
        statusCadEquip = new javax.swing.JComboBox<>();
        FabrCadEquip = new javax.swing.JLabel();
        fabrCadEquip = new javax.swing.JTextField();
        TelefoneCadEquip = new javax.swing.JLabel();
        telefoneCadEquip = new javax.swing.JTextField();
        EmailCadEquip = new javax.swing.JLabel();
        emailCadEquip = new javax.swing.JTextField();
        CadastrarEquip = new javax.swing.JButton();
        EditarEquip = new javax.swing.JButton();
        ExcluirEquip = new javax.swing.JButton();
        AbaReciboEquip = new javax.swing.JPanel();
        Texto1 = new javax.swing.JLabel();
        fabricanteRecEquip = new javax.swing.JTextField();
        Texto2 = new javax.swing.JLabel();
        nomeRecEquip = new javax.swing.JTextField();
        Texto3 = new javax.swing.JLabel();
        dataRecEquip = new com.toedter.calendar.JDateChooser();
        Assinatura1RecEquip = new javax.swing.JLabel();
        Assinatura2RecEquip = new javax.swing.JLabel();
        SalvarRecEquip = new javax.swing.JButton();
        TabelaPesquisaEquip = new javax.swing.JPanel();
        PesquisarEquip = new javax.swing.JButton();
        pesquisarEquip = new javax.swing.JTextField();
        ScrollTabelaEquip = new javax.swing.JScrollPane();
        TabelaEquip = new javax.swing.JTable();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(1000, 640));
        setName("Login"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 640));
        getContentPane().setLayout(null);

        VoltarEquip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Voltar.png"))); // NOI18N
        VoltarEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarEquipActionPerformed(evt);
            }
        });
        getContentPane().add(VoltarEquip);
        VoltarEquip.setBounds(0, 0, 60, 40);

        Titulo.setFont(new java.awt.Font("Impact", 0, 30)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Administrador");
        getContentPane().add(Titulo);
        Titulo.setBounds(0, 10, 1000, 30);

        TelaEquip.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        AbaEquip.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        NomeEquip.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        NomeEquip.setText("Nome:");

        nomeEquip.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nomeEquip.setText("Null");

        IDEquip.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        IDEquip.setText("ID:");

        idEquip.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        idEquip.setText("Null");

        MarcaEquip.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        MarcaEquip.setText("Marca:");

        marcaEquip.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        marcaEquip.setText("Null");

        ManuEquip.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        ManuEquip.setText("Ultima Manutenção:");

        manuEquip.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        manuEquip.setText("Null");

        StatusEquip.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        StatusEquip.setText("Status:");

        statusEquip.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        statusEquip.setText("Null");

        FabricanteEquip.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        FabricanteEquip.setText("Fabricante: ");

        fabricanteEquip.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        fabricanteEquip.setText("Null");

        TelefoneEquip.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        TelefoneEquip.setText("Telefone:");

        telefoneEquip.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        telefoneEquip.setText("Null");
        telefoneEquip.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        EmailEquip.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        EmailEquip.setText("Email:");

        emailEquip.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        emailEquip.setText("Null");
        emailEquip.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout AbaEquipLayout = new javax.swing.GroupLayout(AbaEquip);
        AbaEquip.setLayout(AbaEquipLayout);
        AbaEquipLayout.setHorizontalGroup(
            AbaEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AbaEquipLayout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(AbaEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbaEquipLayout.createSequentialGroup()
                        .addComponent(StatusEquip)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(statusEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AbaEquipLayout.createSequentialGroup()
                        .addComponent(MarcaEquip)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(marcaEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ManuEquip)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(manuEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AbaEquipLayout.createSequentialGroup()
                        .addComponent(NomeEquip)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomeEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(IDEquip)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AbaEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(AbaEquipLayout.createSequentialGroup()
                        .addComponent(EmailEquip)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailEquip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(AbaEquipLayout.createSequentialGroup()
                        .addComponent(TelefoneEquip)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telefoneEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AbaEquipLayout.createSequentialGroup()
                        .addComponent(FabricanteEquip)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fabricanteEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(69, 69, 69))
        );
        AbaEquipLayout.setVerticalGroup(
            AbaEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaEquipLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(AbaEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbaEquipLayout.createSequentialGroup()
                        .addGroup(AbaEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NomeEquip)
                            .addComponent(nomeEquip)
                            .addComponent(IDEquip)
                            .addComponent(idEquip))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AbaEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MarcaEquip)
                            .addComponent(marcaEquip)
                            .addComponent(ManuEquip)
                            .addComponent(manuEquip))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AbaEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StatusEquip)
                            .addComponent(statusEquip)))
                    .addGroup(AbaEquipLayout.createSequentialGroup()
                        .addGroup(AbaEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FabricanteEquip)
                            .addComponent(fabricanteEquip))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AbaEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TelefoneEquip)
                            .addComponent(telefoneEquip))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AbaEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmailEquip)
                            .addComponent(emailEquip))))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        TelaEquip.addTab("Equipamentos", AbaEquip);

        AbaCadEquip.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        NomeCadEquip.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        NomeCadEquip.setText("Nome:");

        nomeCadEquip.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nomeCadEquip.setPreferredSize(new java.awt.Dimension(74, 32));

        IDCadEquip.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        IDCadEquip.setText("ID:");

        idCadEquip.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        idCadEquip.setPreferredSize(new java.awt.Dimension(74, 32));

        MarcaCadEquip.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        MarcaCadEquip.setText("Marca:");

        marcaCadEquip.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        marcaCadEquip.setPreferredSize(new java.awt.Dimension(74, 32));

        ManuCadEquip.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        ManuCadEquip.setText("Ultima Manutenção:");

        manuCadEquip.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        StatusCadEquip.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        StatusCadEquip.setText("Status:");

        statusCadEquip.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        FabrCadEquip.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        FabrCadEquip.setText("Fabricante: ");

        fabrCadEquip.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        fabrCadEquip.setPreferredSize(new java.awt.Dimension(74, 32));

        TelefoneCadEquip.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        TelefoneCadEquip.setText("Telefone:");

        telefoneCadEquip.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        telefoneCadEquip.setPreferredSize(new java.awt.Dimension(74, 32));

        EmailCadEquip.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        EmailCadEquip.setText("Email:");

        emailCadEquip.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        emailCadEquip.setPreferredSize(new java.awt.Dimension(74, 32));

        CadastrarEquip.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        CadastrarEquip.setText("Cadastrar");

        EditarEquip.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        EditarEquip.setText("Editar");

        ExcluirEquip.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        ExcluirEquip.setText("Excluir");

        javax.swing.GroupLayout AbaCadEquipLayout = new javax.swing.GroupLayout(AbaCadEquip);
        AbaCadEquip.setLayout(AbaCadEquipLayout);
        AbaCadEquipLayout.setHorizontalGroup(
            AbaCadEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaCadEquipLayout.createSequentialGroup()
                .addGroup(AbaCadEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbaCadEquipLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(AbaCadEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AbaCadEquipLayout.createSequentialGroup()
                                .addComponent(NomeCadEquip)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomeCadEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(IDCadEquip)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idCadEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AbaCadEquipLayout.createSequentialGroup()
                                .addGroup(AbaCadEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(AbaCadEquipLayout.createSequentialGroup()
                                        .addComponent(MarcaCadEquip)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(marcaCadEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ManuCadEquip))
                                    .addGroup(AbaCadEquipLayout.createSequentialGroup()
                                        .addComponent(StatusCadEquip)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(statusCadEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(manuCadEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(AbaCadEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AbaCadEquipLayout.createSequentialGroup()
                                .addComponent(EmailCadEquip)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emailCadEquip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AbaCadEquipLayout.createSequentialGroup()
                                .addComponent(TelefoneCadEquip)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(telefoneCadEquip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AbaCadEquipLayout.createSequentialGroup()
                                .addComponent(FabrCadEquip)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fabrCadEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(AbaCadEquipLayout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(CadastrarEquip)
                        .addGap(18, 18, 18)
                        .addComponent(EditarEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ExcluirEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        AbaCadEquipLayout.setVerticalGroup(
            AbaCadEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaCadEquipLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(AbaCadEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbaCadEquipLayout.createSequentialGroup()
                        .addGroup(AbaCadEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FabrCadEquip)
                            .addComponent(fabrCadEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AbaCadEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TelefoneCadEquip)
                            .addComponent(telefoneCadEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AbaCadEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmailCadEquip)
                            .addComponent(emailCadEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AbaCadEquipLayout.createSequentialGroup()
                        .addGroup(AbaCadEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NomeCadEquip)
                            .addComponent(IDCadEquip)
                            .addComponent(nomeCadEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idCadEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AbaCadEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AbaCadEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(MarcaCadEquip)
                                .addComponent(ManuCadEquip)
                                .addComponent(marcaCadEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(manuCadEquip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AbaCadEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StatusCadEquip)
                            .addComponent(statusCadEquip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(AbaCadEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditarEquip)
                    .addComponent(CadastrarEquip)
                    .addComponent(ExcluirEquip))
                .addGap(16, 16, 16))
        );

        TelaEquip.addTab("Controle", AbaCadEquip);

        AbaReciboEquip.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Texto1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Texto1.setText("Recebemos de ");

        fabricanteRecEquip.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        fabricanteRecEquip.setPreferredSize(new java.awt.Dimension(74, 32));

        Texto2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Texto2.setText("o produto");

        nomeRecEquip.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nomeRecEquip.setPreferredSize(new java.awt.Dimension(74, 32));

        Texto3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Texto3.setText("correspondente ao pedido de compra referente a data ");

        dataRecEquip.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        Assinatura1RecEquip.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        Assinatura1RecEquip.setText("_________________________________________________");

        Assinatura2RecEquip.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Assinatura2RecEquip.setText("Assinatura");

        SalvarRecEquip.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        SalvarRecEquip.setText("Salvar e Imprimir");
        SalvarRecEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarRecEquipActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AbaReciboEquipLayout = new javax.swing.GroupLayout(AbaReciboEquip);
        AbaReciboEquip.setLayout(AbaReciboEquipLayout);
        AbaReciboEquipLayout.setHorizontalGroup(
            AbaReciboEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaReciboEquipLayout.createSequentialGroup()
                .addGroup(AbaReciboEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbaReciboEquipLayout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addGroup(AbaReciboEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Assinatura1RecEquip)
                            .addGroup(AbaReciboEquipLayout.createSequentialGroup()
                                .addGap(197, 197, 197)
                                .addComponent(Assinatura2RecEquip))))
                    .addGroup(AbaReciboEquipLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(AbaReciboEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AbaReciboEquipLayout.createSequentialGroup()
                                .addComponent(Texto1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fabricanteRecEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Texto2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomeRecEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AbaReciboEquipLayout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(Texto3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dataRecEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(AbaReciboEquipLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SalvarRecEquip)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        AbaReciboEquipLayout.setVerticalGroup(
            AbaReciboEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaReciboEquipLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SalvarRecEquip)
                .addGap(45, 45, 45)
                .addGroup(AbaReciboEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Texto1)
                    .addComponent(fabricanteRecEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Texto2)
                    .addComponent(nomeRecEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AbaReciboEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Texto3)
                    .addComponent(dataRecEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(Assinatura1RecEquip)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Assinatura2RecEquip)
                .addGap(194, 194, 194))
        );

        TelaEquip.addTab("Recibo", AbaReciboEquip);

        getContentPane().add(TelaEquip);
        TelaEquip.setBounds(50, 40, 900, 300);

        TabelaPesquisaEquip.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        PesquisarEquip.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        PesquisarEquip.setText("Pesquisar");

        pesquisarEquip.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        pesquisarEquip.setPreferredSize(new java.awt.Dimension(74, 32));

        TabelaEquip.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TabelaEquip.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TabelaEquip.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "ID", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaEquip.setToolTipText("");
        TabelaEquip.setAlignmentX(1.0F);
        TabelaEquip.setAlignmentY(1.0F);
        TabelaEquip.setRowHeight(28);
        ScrollTabelaEquip.setViewportView(TabelaEquip);

        javax.swing.GroupLayout TabelaPesquisaEquipLayout = new javax.swing.GroupLayout(TabelaPesquisaEquip);
        TabelaPesquisaEquip.setLayout(TabelaPesquisaEquipLayout);
        TabelaPesquisaEquipLayout.setHorizontalGroup(
            TabelaPesquisaEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabelaPesquisaEquipLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PesquisarEquip)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pesquisarEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TabelaPesquisaEquipLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ScrollTabelaEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        TabelaPesquisaEquipLayout.setVerticalGroup(
            TabelaPesquisaEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabelaPesquisaEquipLayout.createSequentialGroup()
                .addGroup(TabelaPesquisaEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PesquisarEquip)
                    .addComponent(pesquisarEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(ScrollTabelaEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(TabelaPesquisaEquip);
        TabelaPesquisaEquip.setBounds(50, 340, 900, 240);

        Background.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        Background.setPreferredSize(new java.awt.Dimension(1000, 570));
        getContentPane().add(Background);
        Background.setBounds(0, 0, 1000, 640);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SalvarRecEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarRecEquipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalvarRecEquipActionPerformed

    private void VoltarEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarEquipActionPerformed
        // Botão Voltar

        AdmSelecao AS = new AdmSelecao();
        AS.setVisible(true);
        dispose();
    }//GEN-LAST:event_VoltarEquipActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpEquipamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpEquipamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpEquipamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpEquipamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpEquipamentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AbaCadEquip;
    private javax.swing.JPanel AbaEquip;
    private javax.swing.JPanel AbaReciboEquip;
    private javax.swing.JLabel Assinatura1RecEquip;
    private javax.swing.JLabel Assinatura2RecEquip;
    private javax.swing.JLabel Background;
    private javax.swing.JButton CadastrarEquip;
    private javax.swing.JButton EditarEquip;
    private javax.swing.JLabel EmailCadEquip;
    private javax.swing.JLabel EmailEquip;
    private javax.swing.JButton ExcluirEquip;
    private javax.swing.JLabel FabrCadEquip;
    private javax.swing.JLabel FabricanteEquip;
    private javax.swing.JLabel IDCadEquip;
    private javax.swing.JLabel IDEquip;
    private javax.swing.JLabel ManuCadEquip;
    private javax.swing.JLabel ManuEquip;
    private javax.swing.JLabel MarcaCadEquip;
    private javax.swing.JLabel MarcaEquip;
    private javax.swing.JLabel NomeCadEquip;
    private javax.swing.JLabel NomeEquip;
    private javax.swing.JButton PesquisarEquip;
    private javax.swing.JButton SalvarRecEquip;
    private javax.swing.JScrollPane ScrollTabelaEquip;
    private javax.swing.JLabel StatusCadEquip;
    private javax.swing.JLabel StatusEquip;
    private javax.swing.JTable TabelaEquip;
    private javax.swing.JPanel TabelaPesquisaEquip;
    private javax.swing.JTabbedPane TelaEquip;
    private javax.swing.JLabel TelefoneCadEquip;
    private javax.swing.JLabel TelefoneEquip;
    private javax.swing.JLabel Texto1;
    private javax.swing.JLabel Texto2;
    private javax.swing.JLabel Texto3;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton VoltarEquip;
    private com.toedter.calendar.JDateChooser dataRecEquip;
    private javax.swing.JTextField emailCadEquip;
    private javax.swing.JLabel emailEquip;
    private javax.swing.JTextField fabrCadEquip;
    private javax.swing.JLabel fabricanteEquip;
    private javax.swing.JTextField fabricanteRecEquip;
    private javax.swing.JTextField idCadEquip;
    private javax.swing.JLabel idEquip;
    private com.toedter.calendar.JDateChooser manuCadEquip;
    private javax.swing.JLabel manuEquip;
    private javax.swing.JTextField marcaCadEquip;
    private javax.swing.JLabel marcaEquip;
    private javax.swing.JTextField nomeCadEquip;
    private javax.swing.JLabel nomeEquip;
    private javax.swing.JTextField nomeRecEquip;
    private javax.swing.JTextField pesquisarEquip;
    private javax.swing.JComboBox<String> statusCadEquip;
    private javax.swing.JLabel statusEquip;
    private javax.swing.JTextField telefoneCadEquip;
    private javax.swing.JLabel telefoneEquip;
    // End of variables declaration//GEN-END:variables
}
