/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AdmAgenServ;

import java.awt.BorderLayout;
import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.JTextField;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import AdmFuncion�rio.*;
import Principal.*;

/**
 *
 * @author GabrielFelipe
 */
public class OpAgendamentoServico extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public OpAgendamentoServico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VoltarAgenServ = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        TelaFunc = new javax.swing.JTabbedPane();
        AbaAgenServ = new javax.swing.JPanel();
        NomeAgenServ = new javax.swing.JLabel();
        nomeAgenServ = new javax.swing.JLabel();
        ObjAgenServ = new javax.swing.JLabel();
        objAgenServ = new javax.swing.JLabel();
        HoraAgenServ = new javax.swing.JLabel();
        horaAgenServ = new javax.swing.JLabel();
        DataAgenServ = new javax.swing.JLabel();
        dataAgenServ = new javax.swing.JLabel();
        RealAgenServ = new javax.swing.JLabel();
        realAgenServ = new javax.swing.JLabel();
        CPFRealAgenServ = new javax.swing.JLabel();
        cpfRealAgenServ = new javax.swing.JLabel();
        DestAgenServ = new javax.swing.JLabel();
        destAgenServ = new javax.swing.JLabel();
        CpfDestAgenServ = new javax.swing.JLabel();
        cpfDestAgenServ = new javax.swing.JLabel();
        AbaCadAgenServ = new javax.swing.JPanel();
        NomeCadAgenServ = new javax.swing.JLabel();
        nomeCadAgenServ = new javax.swing.JTextField();
        ObjCadAgenServ = new javax.swing.JLabel();
        objCadAgenServ = new javax.swing.JTextField();
        HoraCadAgenServ = new javax.swing.JLabel();
        horaCadAgenServ = new javax.swing.JTextField();
        DataCadAgenServ = new javax.swing.JLabel();
        dataCadAgenServ = new com.toedter.calendar.JDateChooser();
        RealCadAgenServ = new javax.swing.JLabel();
        realCadAgenServ = new javax.swing.JTextField();
        CPFRealCadAgenServ = new javax.swing.JLabel();
        cpfRealCadAgenServ = new javax.swing.JTextField();
        DestCadAgenServ = new javax.swing.JLabel();
        destCadAgenServ = new javax.swing.JTextField();
        CpfDestCadAgenServ = new javax.swing.JLabel();
        cpfDestCadAgenServ = new javax.swing.JTextField();
        CadastrarAgenServ = new javax.swing.JButton();
        EditarAgenServ = new javax.swing.JButton();
        ExcluirAgenServ = new javax.swing.JButton();
        AbaCalen = new javax.swing.JPanel();
        calenAgenServ = new com.toedter.calendar.JCalendar();
        TabelaPesquisaAgenServ = new javax.swing.JPanel();
        PesquisarAgenServ = new javax.swing.JButton();
        pesquisarAgenServ = new javax.swing.JTextField();
        ScrollTabelaAgenServ = new javax.swing.JScrollPane();
        TabelaAgenServ = new javax.swing.JTable();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setName("Login"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1000, 640));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 640));
        getContentPane().setLayout(null);

        VoltarAgenServ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Voltar.png"))); // NOI18N
        VoltarAgenServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarAgenServActionPerformed(evt);
            }
        });
        getContentPane().add(VoltarAgenServ);
        VoltarAgenServ.setBounds(0, 0, 60, 40);

        Titulo.setFont(new java.awt.Font("Impact", 0, 30)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Administrador");
        getContentPane().add(Titulo);
        Titulo.setBounds(0, 10, 1000, 30);

        TelaFunc.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        AbaAgenServ.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        NomeAgenServ.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        NomeAgenServ.setText("Nome:");

        nomeAgenServ.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nomeAgenServ.setText("Null");

        ObjAgenServ.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        ObjAgenServ.setText("Objetivo:");

        objAgenServ.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        objAgenServ.setText("Null");

        HoraAgenServ.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        HoraAgenServ.setText("Hora:");

        horaAgenServ.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        horaAgenServ.setText("Null");

        DataAgenServ.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        DataAgenServ.setText("Data:");

        dataAgenServ.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        dataAgenServ.setText("Null");

        RealAgenServ.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        RealAgenServ.setText("Realizador:");

        realAgenServ.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        realAgenServ.setText("Null");

        CPFRealAgenServ.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        CPFRealAgenServ.setText("CPF:");

        cpfRealAgenServ.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cpfRealAgenServ.setText("Null");

        DestAgenServ.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        DestAgenServ.setText("Destinátario:");

        destAgenServ.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        destAgenServ.setText("Null");

        CpfDestAgenServ.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        CpfDestAgenServ.setText("CPF:");

        cpfDestAgenServ.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cpfDestAgenServ.setText("Null");

        javax.swing.GroupLayout AbaAgenServLayout = new javax.swing.GroupLayout(AbaAgenServ);
        AbaAgenServ.setLayout(AbaAgenServLayout);
        AbaAgenServLayout.setHorizontalGroup(
            AbaAgenServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaAgenServLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(AbaAgenServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AbaAgenServLayout.createSequentialGroup()
                        .addGroup(AbaAgenServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AbaAgenServLayout.createSequentialGroup()
                                .addComponent(ObjAgenServ)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(objAgenServ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(AbaAgenServLayout.createSequentialGroup()
                                .addComponent(NomeAgenServ)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomeAgenServ, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(60, 60, 60))
                    .addGroup(AbaAgenServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AbaAgenServLayout.createSequentialGroup()
                            .addComponent(DataAgenServ)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(dataAgenServ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AbaAgenServLayout.createSequentialGroup()
                            .addComponent(HoraAgenServ)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(horaAgenServ, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(AbaAgenServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbaAgenServLayout.createSequentialGroup()
                        .addGroup(AbaAgenServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DestAgenServ)
                            .addComponent(CpfDestAgenServ))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AbaAgenServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(destAgenServ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cpfDestAgenServ, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AbaAgenServLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(AbaAgenServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RealAgenServ)
                            .addComponent(CPFRealAgenServ))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AbaAgenServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(realAgenServ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cpfRealAgenServ, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        AbaAgenServLayout.setVerticalGroup(
            AbaAgenServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaAgenServLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(AbaAgenServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbaAgenServLayout.createSequentialGroup()
                        .addGroup(AbaAgenServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RealAgenServ)
                            .addComponent(nomeAgenServ)
                            .addComponent(realAgenServ))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AbaAgenServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CPFRealAgenServ)
                            .addComponent(cpfRealAgenServ))
                        .addGap(18, 18, 18)
                        .addGroup(AbaAgenServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DestAgenServ)
                            .addComponent(destAgenServ))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AbaAgenServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CpfDestAgenServ)
                            .addComponent(cpfDestAgenServ)))
                    .addGroup(AbaAgenServLayout.createSequentialGroup()
                        .addComponent(NomeAgenServ)
                        .addGap(18, 18, 18)
                        .addGroup(AbaAgenServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ObjAgenServ)
                            .addComponent(objAgenServ))
                        .addGap(18, 18, 18)
                        .addGroup(AbaAgenServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HoraAgenServ)
                            .addComponent(horaAgenServ))
                        .addGap(11, 11, 11)
                        .addGroup(AbaAgenServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DataAgenServ)
                            .addComponent(dataAgenServ))))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        TelaFunc.addTab("Serviços", AbaAgenServ);

        AbaCadAgenServ.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        NomeCadAgenServ.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        NomeCadAgenServ.setText("Nome:");

        nomeCadAgenServ.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        ObjCadAgenServ.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        ObjCadAgenServ.setText("Objetivo:");

        objCadAgenServ.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        HoraCadAgenServ.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        HoraCadAgenServ.setText("Hora:");

        horaCadAgenServ.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        DataCadAgenServ.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        DataCadAgenServ.setText("Data:");

        dataCadAgenServ.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        RealCadAgenServ.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        RealCadAgenServ.setText("Realizador:");

        realCadAgenServ.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        CPFRealCadAgenServ.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        CPFRealCadAgenServ.setText("CPF:");

        cpfRealCadAgenServ.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        DestCadAgenServ.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        DestCadAgenServ.setText("Destinátario:");

        destCadAgenServ.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        CpfDestCadAgenServ.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        CpfDestCadAgenServ.setText("CPF:");

        cpfDestCadAgenServ.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        CadastrarAgenServ.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        CadastrarAgenServ.setText("Cadastrar");

        EditarAgenServ.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        EditarAgenServ.setText("Editar");

        ExcluirAgenServ.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        ExcluirAgenServ.setText("Excluir");

        javax.swing.GroupLayout AbaCadAgenServLayout = new javax.swing.GroupLayout(AbaCadAgenServ);
        AbaCadAgenServ.setLayout(AbaCadAgenServLayout);
        AbaCadAgenServLayout.setHorizontalGroup(
            AbaCadAgenServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaCadAgenServLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(AbaCadAgenServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(AbaCadAgenServLayout.createSequentialGroup()
                        .addComponent(HoraCadAgenServ)
                        .addGap(6, 6, 6)
                        .addComponent(horaCadAgenServ, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AbaCadAgenServLayout.createSequentialGroup()
                        .addComponent(NomeCadAgenServ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeCadAgenServ, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AbaCadAgenServLayout.createSequentialGroup()
                        .addComponent(DataCadAgenServ)
                        .addGap(7, 7, 7)
                        .addComponent(dataCadAgenServ, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AbaCadAgenServLayout.createSequentialGroup()
                        .addComponent(ObjCadAgenServ)
                        .addGap(9, 9, 9)
                        .addComponent(objCadAgenServ, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(AbaCadAgenServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(AbaCadAgenServLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(AbaCadAgenServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RealCadAgenServ)
                            .addComponent(CPFRealCadAgenServ))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AbaCadAgenServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cpfRealCadAgenServ)
                            .addComponent(realCadAgenServ, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AbaCadAgenServLayout.createSequentialGroup()
                        .addGroup(AbaCadAgenServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DestCadAgenServ)
                            .addComponent(CpfDestCadAgenServ))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AbaCadAgenServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(destCadAgenServ, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpfDestCadAgenServ, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(AbaCadAgenServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ExcluirAgenServ, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CadastrarAgenServ)
                    .addComponent(EditarAgenServ, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
        );
        AbaCadAgenServLayout.setVerticalGroup(
            AbaCadAgenServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaCadAgenServLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(AbaCadAgenServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbaCadAgenServLayout.createSequentialGroup()
                        .addGroup(AbaCadAgenServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NomeCadAgenServ)
                            .addComponent(nomeCadAgenServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AbaCadAgenServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ObjCadAgenServ)
                            .addComponent(objCadAgenServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AbaCadAgenServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HoraCadAgenServ)
                            .addComponent(horaCadAgenServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(AbaCadAgenServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DataCadAgenServ)
                            .addComponent(dataCadAgenServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AbaCadAgenServLayout.createSequentialGroup()
                        .addGroup(AbaCadAgenServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RealCadAgenServ)
                            .addComponent(realCadAgenServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AbaCadAgenServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CPFRealCadAgenServ)
                            .addComponent(cpfRealCadAgenServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AbaCadAgenServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(destCadAgenServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DestCadAgenServ))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AbaCadAgenServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cpfDestCadAgenServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CpfDestCadAgenServ)))
                    .addGroup(AbaCadAgenServLayout.createSequentialGroup()
                        .addComponent(CadastrarAgenServ)
                        .addGap(18, 18, 18)
                        .addComponent(EditarAgenServ)
                        .addGap(18, 18, 18)
                        .addComponent(ExcluirAgenServ)))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        TelaFunc.addTab("Controle", AbaCadAgenServ);

        AbaCalen.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        calenAgenServ.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        javax.swing.GroupLayout AbaCalenLayout = new javax.swing.GroupLayout(AbaCalen);
        AbaCalen.setLayout(AbaCalenLayout);
        AbaCalenLayout.setHorizontalGroup(
            AbaCalenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaCalenLayout.createSequentialGroup()
                .addComponent(calenAgenServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 375, Short.MAX_VALUE))
        );
        AbaCalenLayout.setVerticalGroup(
            AbaCalenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaCalenLayout.createSequentialGroup()
                .addComponent(calenAgenServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        TelaFunc.addTab("Calendário", AbaCalen);

        getContentPane().add(TelaFunc);
        TelaFunc.setBounds(50, 40, 900, 300);

        TabelaPesquisaAgenServ.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        PesquisarAgenServ.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        PesquisarAgenServ.setText("Pesquisar");

        pesquisarAgenServ.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        pesquisarAgenServ.setPreferredSize(new java.awt.Dimension(74, 32));

        TabelaAgenServ.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TabelaAgenServ.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TabelaAgenServ.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Serviço", "Data"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaAgenServ.setToolTipText("");
        TabelaAgenServ.setAlignmentX(1.0F);
        TabelaAgenServ.setAlignmentY(1.0F);
        TabelaAgenServ.setRowHeight(28);
        ScrollTabelaAgenServ.setViewportView(TabelaAgenServ);

        javax.swing.GroupLayout TabelaPesquisaAgenServLayout = new javax.swing.GroupLayout(TabelaPesquisaAgenServ);
        TabelaPesquisaAgenServ.setLayout(TabelaPesquisaAgenServLayout);
        TabelaPesquisaAgenServLayout.setHorizontalGroup(
            TabelaPesquisaAgenServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabelaPesquisaAgenServLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PesquisarAgenServ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pesquisarAgenServ, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TabelaPesquisaAgenServLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ScrollTabelaAgenServ, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        TabelaPesquisaAgenServLayout.setVerticalGroup(
            TabelaPesquisaAgenServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabelaPesquisaAgenServLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TabelaPesquisaAgenServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PesquisarAgenServ)
                    .addComponent(pesquisarAgenServ, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ScrollTabelaAgenServ, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(TabelaPesquisaAgenServ);
        TabelaPesquisaAgenServ.setBounds(50, 340, 900, 240);

        Background.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        Background.setPreferredSize(new java.awt.Dimension(1000, 570));
        getContentPane().add(Background);
        Background.setBounds(0, 0, 1000, 640);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarAgenServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarAgenServActionPerformed
        // Botão Voltar

        AdmSelecao AS = new AdmSelecao();
        AS.setVisible(true);
        dispose();
    }//GEN-LAST:event_VoltarAgenServActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpAgendamentoServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpAgendamentoServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpAgendamentoServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpAgendamentoServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpAgendamentoServico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AbaAgenServ;
    private javax.swing.JPanel AbaCadAgenServ;
    private javax.swing.JPanel AbaCalen;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel CPFRealAgenServ;
    private javax.swing.JLabel CPFRealCadAgenServ;
    private javax.swing.JButton CadastrarAgenServ;
    private javax.swing.JLabel CpfDestAgenServ;
    private javax.swing.JLabel CpfDestCadAgenServ;
    private javax.swing.JLabel DataAgenServ;
    private javax.swing.JLabel DataCadAgenServ;
    private javax.swing.JLabel DestAgenServ;
    private javax.swing.JLabel DestCadAgenServ;
    private javax.swing.JButton EditarAgenServ;
    private javax.swing.JButton ExcluirAgenServ;
    private javax.swing.JLabel HoraAgenServ;
    private javax.swing.JLabel HoraCadAgenServ;
    private javax.swing.JLabel NomeAgenServ;
    private javax.swing.JLabel NomeCadAgenServ;
    private javax.swing.JLabel ObjAgenServ;
    private javax.swing.JLabel ObjCadAgenServ;
    private javax.swing.JButton PesquisarAgenServ;
    private javax.swing.JLabel RealAgenServ;
    private javax.swing.JLabel RealCadAgenServ;
    private javax.swing.JScrollPane ScrollTabelaAgenServ;
    private javax.swing.JTable TabelaAgenServ;
    private javax.swing.JPanel TabelaPesquisaAgenServ;
    private javax.swing.JTabbedPane TelaFunc;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton VoltarAgenServ;
    private com.toedter.calendar.JCalendar calenAgenServ;
    private javax.swing.JLabel cpfDestAgenServ;
    private javax.swing.JTextField cpfDestCadAgenServ;
    private javax.swing.JLabel cpfRealAgenServ;
    private javax.swing.JTextField cpfRealCadAgenServ;
    private javax.swing.JLabel dataAgenServ;
    private com.toedter.calendar.JDateChooser dataCadAgenServ;
    private javax.swing.JLabel destAgenServ;
    private javax.swing.JTextField destCadAgenServ;
    private javax.swing.JLabel horaAgenServ;
    private javax.swing.JTextField horaCadAgenServ;
    private javax.swing.JLabel nomeAgenServ;
    private javax.swing.JTextField nomeCadAgenServ;
    private javax.swing.JLabel objAgenServ;
    private javax.swing.JTextField objCadAgenServ;
    private javax.swing.JTextField pesquisarAgenServ;
    private javax.swing.JLabel realAgenServ;
    private javax.swing.JTextField realCadAgenServ;
    // End of variables declaration//GEN-END:variables
}
