/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AdmTurmas;

import AdmAgenServ.*;
import AdmFuncion�rio.*;
import Principal.*;

/**
 *
 * @author GabrielFelipe
 */
public class OpTurma extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public OpTurma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VoltarTurma = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        TelaFunc = new javax.swing.JTabbedPane();
        AbaTurma = new javax.swing.JPanel();
        NomeTurma = new javax.swing.JLabel();
        nomeTurma = new javax.swing.JLabel();
        IDTurma = new javax.swing.JLabel();
        idTurma = new javax.swing.JLabel();
        InstrTurma = new javax.swing.JLabel();
        instrTurma = new javax.swing.JLabel();
        HorariosTurma = new javax.swing.JPanel();
        TituloHorarios = new javax.swing.JLabel();
        Horario1 = new javax.swing.JCheckBox();
        Horario2 = new javax.swing.JCheckBox();
        Horario3 = new javax.swing.JCheckBox();
        Horario4 = new javax.swing.JCheckBox();
        Horario5 = new javax.swing.JCheckBox();
        PesquisarAlunTurma = new javax.swing.JButton();
        pesquisarAlunTurma = new javax.swing.JTextField();
        ScrollTabelaAlunTurma = new javax.swing.JScrollPane();
        TabelaAlunTurma = new javax.swing.JTable();
        AbaCadAlunTurma = new javax.swing.JPanel();
        fotoCadAlunTurma = new javax.swing.JLabel();
        NomeCadAlunTurma = new javax.swing.JLabel();
        nomeCadAlunTurma = new javax.swing.JLabel();
        CPFCadAlunTurma = new javax.swing.JLabel();
        cpfCadAlunTurma = new javax.swing.JLabel();
        TelefoneCadAlunTurma = new javax.swing.JLabel();
        telefoneCadAlunTurma = new javax.swing.JLabel();
        EmailCadAlunTurma = new javax.swing.JLabel();
        emailCadAlunTurma = new javax.swing.JLabel();
        PesquisarCadAlunTurma = new javax.swing.JButton();
        pesquisarCadAlunTurma = new javax.swing.JTextField();
        ScrollTabelaCadAlunTurma = new javax.swing.JScrollPane();
        TabelaCadAlunTurma = new javax.swing.JTable();
        CadastrarAlunTurma = new javax.swing.JButton();
        ExcluirAlunTurma = new javax.swing.JButton();
        AbaCadTurma = new javax.swing.JPanel();
        NomeCadTurma = new javax.swing.JLabel();
        nomeCadTurma = new javax.swing.JTextField();
        IDCadTurma = new javax.swing.JLabel();
        idCadTurma = new javax.swing.JTextField();
        InstrCadTurma = new javax.swing.JLabel();
        instrCadTurma = new javax.swing.JComboBox<>();
        HorariosCadTurma = new javax.swing.JPanel();
        TituloHoCadTurma = new javax.swing.JLabel();
        HorarioCadTurma1 = new javax.swing.JCheckBox();
        HorarioCadTurma2 = new javax.swing.JCheckBox();
        HorarioCadTurma3 = new javax.swing.JCheckBox();
        HorarioCadTurma4 = new javax.swing.JCheckBox();
        HorarioCadTurma5 = new javax.swing.JCheckBox();
        CadastrarCadTurma = new javax.swing.JButton();
        EditarCadTurma = new javax.swing.JButton();
        ExcluirCadTurma = new javax.swing.JButton();
        TabelaPesquisaTurma = new javax.swing.JPanel();
        PesquisarTurma = new javax.swing.JButton();
        pesquisarTurma = new javax.swing.JTextField();
        ScrollTabelaTurma = new javax.swing.JScrollPane();
        TabelaTurma = new javax.swing.JTable();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(1000, 640));
        setName("Login"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 640));
        getContentPane().setLayout(null);

        VoltarTurma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Voltar.png"))); // NOI18N
        VoltarTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarTurmaActionPerformed(evt);
            }
        });
        getContentPane().add(VoltarTurma);
        VoltarTurma.setBounds(0, 0, 60, 40);

        Titulo.setFont(new java.awt.Font("Impact", 0, 30)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Administrador");
        getContentPane().add(Titulo);
        Titulo.setBounds(0, 10, 1000, 30);

        TelaFunc.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        AbaTurma.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        NomeTurma.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        NomeTurma.setText("Nome:");

        nomeTurma.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nomeTurma.setText("Null");

        IDTurma.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        IDTurma.setText("ID:");

        idTurma.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        idTurma.setText("Null");

        InstrTurma.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        InstrTurma.setText("Instrutor:");

        instrTurma.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        instrTurma.setText("Null");

        HorariosTurma.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TituloHorarios.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        TituloHorarios.setText("Horarios:");

        Horario1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Horario1.setText("13:00 ás 15:00");
        Horario1.setEnabled(false);

        Horario2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Horario2.setText("15:00 ás 17:00");
        Horario2.setEnabled(false);

        Horario3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Horario3.setText("17:00 ás 19:00");
        Horario3.setEnabled(false);
        Horario3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Horario3ActionPerformed(evt);
            }
        });

        Horario4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Horario4.setText("19:00 ás 21:00");
        Horario4.setEnabled(false);

        Horario5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Horario5.setText("21:00 ás 23:00");
        Horario5.setEnabled(false);

        javax.swing.GroupLayout HorariosTurmaLayout = new javax.swing.GroupLayout(HorariosTurma);
        HorariosTurma.setLayout(HorariosTurmaLayout);
        HorariosTurmaLayout.setHorizontalGroup(
            HorariosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HorariosTurmaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HorariosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HorariosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HorariosTurmaLayout.createSequentialGroup()
                            .addComponent(TituloHorarios)
                            .addGap(42, 42, 42))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HorariosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Horario1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Horario2)
                            .addComponent(Horario3)
                            .addComponent(Horario4)))
                    .addComponent(Horario5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HorariosTurmaLayout.setVerticalGroup(
            HorariosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HorariosTurmaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TituloHorarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Horario1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Horario2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Horario3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Horario4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Horario5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PesquisarAlunTurma.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        PesquisarAlunTurma.setText("Pesquisar Aluno");

        pesquisarAlunTurma.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        pesquisarAlunTurma.setPreferredSize(new java.awt.Dimension(74, 32));

        TabelaAlunTurma.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TabelaAlunTurma.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TabelaAlunTurma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "CPF"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaAlunTurma.setToolTipText("");
        TabelaAlunTurma.setAlignmentX(1.0F);
        TabelaAlunTurma.setAlignmentY(1.0F);
        TabelaAlunTurma.setRowHeight(28);
        ScrollTabelaAlunTurma.setViewportView(TabelaAlunTurma);

        javax.swing.GroupLayout AbaTurmaLayout = new javax.swing.GroupLayout(AbaTurma);
        AbaTurma.setLayout(AbaTurmaLayout);
        AbaTurmaLayout.setHorizontalGroup(
            AbaTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaTurmaLayout.createSequentialGroup()
                .addGroup(AbaTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbaTurmaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(AbaTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AbaTurmaLayout.createSequentialGroup()
                                .addComponent(InstrTurma)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(instrTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AbaTurmaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(AbaTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NomeTurma)
                                    .addComponent(IDTurma))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(AbaTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(idTurma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nomeTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18))
                    .addGroup(AbaTurmaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PesquisarAlunTurma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pesquisarAlunTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(HorariosTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ScrollTabelaAlunTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        AbaTurmaLayout.setVerticalGroup(
            AbaTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaTurmaLayout.createSequentialGroup()
                .addGroup(AbaTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbaTurmaLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(AbaTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HorariosTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ScrollTabelaAlunTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AbaTurmaLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(AbaTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AbaTurmaLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(AbaTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(IDTurma)
                                    .addComponent(idTurma)))
                            .addGroup(AbaTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nomeTurma)
                                .addComponent(NomeTurma)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AbaTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InstrTurma)
                            .addComponent(instrTurma))
                        .addGap(18, 18, 18)
                        .addGroup(AbaTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PesquisarAlunTurma)
                            .addComponent(pesquisarAlunTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(243, 243, 243))
        );

        TelaFunc.addTab("Turmas", AbaTurma);

        AbaCadAlunTurma.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        fotoCadAlunTurma.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        NomeCadAlunTurma.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        NomeCadAlunTurma.setText("Nome:");

        nomeCadAlunTurma.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nomeCadAlunTurma.setText("Null");

        CPFCadAlunTurma.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        CPFCadAlunTurma.setText("CPF:");

        cpfCadAlunTurma.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cpfCadAlunTurma.setText("Null");

        TelefoneCadAlunTurma.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        TelefoneCadAlunTurma.setText("Telefone:");

        telefoneCadAlunTurma.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        telefoneCadAlunTurma.setText("Null");

        EmailCadAlunTurma.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        EmailCadAlunTurma.setText("Email:");

        emailCadAlunTurma.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        emailCadAlunTurma.setText("Null");

        PesquisarCadAlunTurma.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        PesquisarCadAlunTurma.setText("Pesquisar Aluno");

        pesquisarCadAlunTurma.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        pesquisarCadAlunTurma.setPreferredSize(new java.awt.Dimension(74, 32));

        TabelaCadAlunTurma.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TabelaCadAlunTurma.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TabelaCadAlunTurma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "CPF"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaCadAlunTurma.setToolTipText("");
        TabelaCadAlunTurma.setAlignmentX(1.0F);
        TabelaCadAlunTurma.setAlignmentY(1.0F);
        TabelaCadAlunTurma.setRowHeight(28);
        ScrollTabelaCadAlunTurma.setViewportView(TabelaCadAlunTurma);

        CadastrarAlunTurma.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        CadastrarAlunTurma.setText("Cadastrar");

        ExcluirAlunTurma.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        ExcluirAlunTurma.setText("Excluir");

        javax.swing.GroupLayout AbaCadAlunTurmaLayout = new javax.swing.GroupLayout(AbaCadAlunTurma);
        AbaCadAlunTurma.setLayout(AbaCadAlunTurmaLayout);
        AbaCadAlunTurmaLayout.setHorizontalGroup(
            AbaCadAlunTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaCadAlunTurmaLayout.createSequentialGroup()
                .addGroup(AbaCadAlunTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbaCadAlunTurmaLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(PesquisarCadAlunTurma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pesquisarCadAlunTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE))
                    .addGroup(AbaCadAlunTurmaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(fotoCadAlunTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(AbaCadAlunTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AbaCadAlunTurmaLayout.createSequentialGroup()
                                .addComponent(EmailCadAlunTurma)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emailCadAlunTurma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(AbaCadAlunTurmaLayout.createSequentialGroup()
                                .addComponent(TelefoneCadAlunTurma)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(telefoneCadAlunTurma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(AbaCadAlunTurmaLayout.createSequentialGroup()
                                .addComponent(NomeCadAlunTurma)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomeCadAlunTurma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AbaCadAlunTurmaLayout.createSequentialGroup()
                                .addComponent(CPFCadAlunTurma)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cpfCadAlunTurma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(6, 6, 6)))
                .addComponent(ScrollTabelaCadAlunTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(AbaCadAlunTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CadastrarAlunTurma)
                    .addComponent(ExcluirAlunTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        AbaCadAlunTurmaLayout.setVerticalGroup(
            AbaCadAlunTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaCadAlunTurmaLayout.createSequentialGroup()
                .addGroup(AbaCadAlunTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbaCadAlunTurmaLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(AbaCadAlunTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ScrollTabelaCadAlunTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AbaCadAlunTurmaLayout.createSequentialGroup()
                                .addGroup(AbaCadAlunTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(AbaCadAlunTurmaLayout.createSequentialGroup()
                                        .addGroup(AbaCadAlunTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(NomeCadAlunTurma)
                                            .addComponent(nomeCadAlunTurma))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(AbaCadAlunTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(CPFCadAlunTurma)
                                            .addComponent(cpfCadAlunTurma))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(AbaCadAlunTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(TelefoneCadAlunTurma)
                                            .addComponent(telefoneCadAlunTurma))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(AbaCadAlunTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(EmailCadAlunTurma)
                                            .addComponent(emailCadAlunTurma)))
                                    .addGroup(AbaCadAlunTurmaLayout.createSequentialGroup()
                                        .addComponent(fotoCadAlunTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)))
                                .addGroup(AbaCadAlunTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(PesquisarCadAlunTurma)
                                    .addComponent(pesquisarCadAlunTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(AbaCadAlunTurmaLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(CadastrarAlunTurma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ExcluirAlunTurma)))
                .addGap(243, 243, 243))
        );

        TelaFunc.addTab("Alunos", AbaCadAlunTurma);

        AbaCadTurma.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        NomeCadTurma.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        NomeCadTurma.setText("Nome:");

        nomeCadTurma.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        IDCadTurma.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        IDCadTurma.setText("ID:");

        idCadTurma.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        InstrCadTurma.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        InstrCadTurma.setText("Instrutor:");

        instrCadTurma.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        HorariosCadTurma.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TituloHoCadTurma.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        TituloHoCadTurma.setText("Horarios:");

        HorarioCadTurma1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        HorarioCadTurma1.setText("13:00 ás 15:00");

        HorarioCadTurma2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        HorarioCadTurma2.setText("15:00 ás 17:00");

        HorarioCadTurma3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        HorarioCadTurma3.setText("17:00 ás 19:00");
        HorarioCadTurma3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HorarioCadTurma3ActionPerformed(evt);
            }
        });

        HorarioCadTurma4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        HorarioCadTurma4.setText("19:00 ás 21:00");

        HorarioCadTurma5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        HorarioCadTurma5.setText("21:00 ás 23:00");

        javax.swing.GroupLayout HorariosCadTurmaLayout = new javax.swing.GroupLayout(HorariosCadTurma);
        HorariosCadTurma.setLayout(HorariosCadTurmaLayout);
        HorariosCadTurmaLayout.setHorizontalGroup(
            HorariosCadTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HorariosCadTurmaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HorariosCadTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HorariosCadTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HorariosCadTurmaLayout.createSequentialGroup()
                            .addComponent(TituloHoCadTurma)
                            .addGap(42, 42, 42))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HorariosCadTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HorarioCadTurma1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(HorarioCadTurma2)
                            .addComponent(HorarioCadTurma3)
                            .addComponent(HorarioCadTurma4)))
                    .addComponent(HorarioCadTurma5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HorariosCadTurmaLayout.setVerticalGroup(
            HorariosCadTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HorariosCadTurmaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TituloHoCadTurma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HorarioCadTurma1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HorarioCadTurma2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HorarioCadTurma3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HorarioCadTurma4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HorarioCadTurma5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CadastrarCadTurma.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        CadastrarCadTurma.setText("Cadastrar");

        EditarCadTurma.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        EditarCadTurma.setText("Editar");

        ExcluirCadTurma.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        ExcluirCadTurma.setText("Excluir");

        javax.swing.GroupLayout AbaCadTurmaLayout = new javax.swing.GroupLayout(AbaCadTurma);
        AbaCadTurma.setLayout(AbaCadTurmaLayout);
        AbaCadTurmaLayout.setHorizontalGroup(
            AbaCadTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AbaCadTurmaLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(AbaCadTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InstrCadTurma, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NomeCadTurma, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(IDCadTurma, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AbaCadTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nomeCadTurma)
                    .addComponent(idCadTurma)
                    .addComponent(instrCadTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(HorariosCadTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addGroup(AbaCadTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ExcluirCadTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CadastrarCadTurma)
                    .addComponent(EditarCadTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105))
        );
        AbaCadTurmaLayout.setVerticalGroup(
            AbaCadTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaCadTurmaLayout.createSequentialGroup()
                .addGroup(AbaCadTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbaCadTurmaLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(AbaCadTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AbaCadTurmaLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(AbaCadTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(IDCadTurma)
                                    .addComponent(idCadTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(AbaCadTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(NomeCadTurma)
                                .addComponent(nomeCadTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AbaCadTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InstrCadTurma)
                            .addComponent(instrCadTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AbaCadTurmaLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(CadastrarCadTurma)
                        .addGap(18, 18, 18)
                        .addComponent(EditarCadTurma)
                        .addGap(18, 18, 18)
                        .addComponent(ExcluirCadTurma))
                    .addGroup(AbaCadTurmaLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(HorariosCadTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        TelaFunc.addTab("Controle", AbaCadTurma);

        getContentPane().add(TelaFunc);
        TelaFunc.setBounds(50, 40, 900, 300);

        TabelaPesquisaTurma.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        PesquisarTurma.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        PesquisarTurma.setText("Pesquisar Turma");

        pesquisarTurma.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        pesquisarTurma.setPreferredSize(new java.awt.Dimension(74, 32));

        TabelaTurma.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TabelaTurma.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TabelaTurma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "ID", "Instrutor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaTurma.setToolTipText("");
        TabelaTurma.setAlignmentX(1.0F);
        TabelaTurma.setAlignmentY(1.0F);
        TabelaTurma.setRowHeight(28);
        ScrollTabelaTurma.setViewportView(TabelaTurma);

        javax.swing.GroupLayout TabelaPesquisaTurmaLayout = new javax.swing.GroupLayout(TabelaPesquisaTurma);
        TabelaPesquisaTurma.setLayout(TabelaPesquisaTurmaLayout);
        TabelaPesquisaTurmaLayout.setHorizontalGroup(
            TabelaPesquisaTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabelaPesquisaTurmaLayout.createSequentialGroup()
                .addGroup(TabelaPesquisaTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TabelaPesquisaTurmaLayout.createSequentialGroup()
                        .addComponent(PesquisarTurma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pesquisarTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ScrollTabelaTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        TabelaPesquisaTurmaLayout.setVerticalGroup(
            TabelaPesquisaTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabelaPesquisaTurmaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TabelaPesquisaTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PesquisarTurma)
                    .addComponent(pesquisarTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ScrollTabelaTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(TabelaPesquisaTurma);
        TabelaPesquisaTurma.setBounds(50, 340, 900, 240);

        Background.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        Background.setPreferredSize(new java.awt.Dimension(1000, 570));
        getContentPane().add(Background);
        Background.setBounds(0, 0, 1000, 640);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Horario3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Horario3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Horario3ActionPerformed

    private void HorarioCadTurma3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HorarioCadTurma3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HorarioCadTurma3ActionPerformed

    private void VoltarTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarTurmaActionPerformed
        // Botão Voltar

        AdmSelecao AS = new AdmSelecao();
        AS.setVisible(true);
        dispose();
    }//GEN-LAST:event_VoltarTurmaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpTurma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AbaCadAlunTurma;
    private javax.swing.JPanel AbaCadTurma;
    private javax.swing.JPanel AbaTurma;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel CPFCadAlunTurma;
    private javax.swing.JButton CadastrarAlunTurma;
    private javax.swing.JButton CadastrarCadTurma;
    private javax.swing.JButton EditarCadTurma;
    private javax.swing.JLabel EmailCadAlunTurma;
    private javax.swing.JButton ExcluirAlunTurma;
    private javax.swing.JButton ExcluirCadTurma;
    private javax.swing.JCheckBox Horario1;
    private javax.swing.JCheckBox Horario2;
    private javax.swing.JCheckBox Horario3;
    private javax.swing.JCheckBox Horario4;
    private javax.swing.JCheckBox Horario5;
    private javax.swing.JCheckBox HorarioCadTurma1;
    private javax.swing.JCheckBox HorarioCadTurma2;
    private javax.swing.JCheckBox HorarioCadTurma3;
    private javax.swing.JCheckBox HorarioCadTurma4;
    private javax.swing.JCheckBox HorarioCadTurma5;
    private javax.swing.JPanel HorariosCadTurma;
    private javax.swing.JPanel HorariosTurma;
    private javax.swing.JLabel IDCadTurma;
    private javax.swing.JLabel IDTurma;
    private javax.swing.JLabel InstrCadTurma;
    private javax.swing.JLabel InstrTurma;
    private javax.swing.JLabel NomeCadAlunTurma;
    private javax.swing.JLabel NomeCadTurma;
    private javax.swing.JLabel NomeTurma;
    private javax.swing.JButton PesquisarAlunTurma;
    private javax.swing.JButton PesquisarCadAlunTurma;
    private javax.swing.JButton PesquisarTurma;
    private javax.swing.JScrollPane ScrollTabelaAlunTurma;
    private javax.swing.JScrollPane ScrollTabelaCadAlunTurma;
    private javax.swing.JScrollPane ScrollTabelaTurma;
    private javax.swing.JTable TabelaAlunTurma;
    private javax.swing.JTable TabelaCadAlunTurma;
    private javax.swing.JPanel TabelaPesquisaTurma;
    private javax.swing.JTable TabelaTurma;
    private javax.swing.JTabbedPane TelaFunc;
    private javax.swing.JLabel TelefoneCadAlunTurma;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel TituloHoCadTurma;
    private javax.swing.JLabel TituloHorarios;
    private javax.swing.JButton VoltarTurma;
    private javax.swing.JLabel cpfCadAlunTurma;
    private javax.swing.JLabel emailCadAlunTurma;
    private javax.swing.JLabel fotoCadAlunTurma;
    private javax.swing.JTextField idCadTurma;
    private javax.swing.JLabel idTurma;
    private javax.swing.JComboBox<String> instrCadTurma;
    private javax.swing.JLabel instrTurma;
    private javax.swing.JLabel nomeCadAlunTurma;
    private javax.swing.JTextField nomeCadTurma;
    private javax.swing.JLabel nomeTurma;
    private javax.swing.JTextField pesquisarAlunTurma;
    private javax.swing.JTextField pesquisarCadAlunTurma;
    private javax.swing.JTextField pesquisarTurma;
    private javax.swing.JLabel telefoneCadAlunTurma;
    // End of variables declaration//GEN-END:variables
}
